#ifndef XVT_XVT_TYPEDEFS_H
#define XVT_XVT_TYPEDEFS_H

#include "aeron/compat/dplay.h"
#include "aeron/compat/dsound.h"

/* Forward typedefs for every structure recovered from the
 * IDB. The defining module header declares the layout; pointer
 * references only need these names. Generated with the skeleton;
 * keep in sync with the IDB local types. */

#ifdef __cplusplus
extern "C" {
#endif

struct ActiveSoundInstance;
struct AiController;
struct AiFlightState;
struct AiOrderProgress;
struct BattleContinuation;
struct BattleSequenceState;
struct BitmapFont;
struct BriefingMapS16Pair;
struct CDAudioTrackCache;
struct CampaignAwardSpriteEntry;
struct CampaignContinuation;
struct CampaignSequenceState;
struct ColorInfo;
struct CraftDamageStats;
struct CraftData;
struct CraftLaserState;
struct CraftTechStats;
struct CraftWeaponSlot;
struct CraftWeaponStats;
struct CutsceneEntry;
/* Original Windows spellings for Aeron's shared DirectSound ABI types. */
typedef DSBufferCaps DSBCAPS;
typedef DSBufferDesc DSBUFFERDESC;
typedef DSoundDeviceCaps DSCAPS;
struct DirectSoundBufferSet;
struct EAIStruct;
struct ECondStruct;
struct EFGStruct;
struct EMissionGoal;
struct EMissionStruct;
struct FaceRecord;
struct FaceTextureGradients;
struct FlightRadarMarkerOffset;
struct FlightGlobalCountdownTimers;
struct FlightGroupGoal;
struct FlightInputFrameRecord;
struct FlightLaunchArgs;
struct FlightMissionState;
struct FlightNetInputBatchPacket;
struct FlightNetScratchPacket;
struct FlightNetWorldStateChunkPacket;
struct FlightSwMarkerOffset;
struct FlightSwRotSpriteCoeffState;
struct FlightSwRotSpriteEdgePoint;
struct FlightSwRotSpriteScaleState;
struct FlightSwRotSpriteSpanRun;
struct FlightViewportSaveState;
struct FrontImageResourceRecord;
struct FrontImageRleRowBuffer;
struct FrontendBriefingScript;
struct FrontendFileList;
struct FrontendFileListNode;
struct FrontendMission;
struct FrontendMissionHeader;
struct FrontendNetPacketScratch;
struct FrontendNetSessionEntry;
struct FrontendScreenState;
struct FrontendSoundBufferRecord;
struct FrontendSoundVoice;
struct GameConfig;
struct GlobalGoal;
struct HudBeamSegmentOffset;
struct HudCockpitResource;
struct HudCockpitResourceDescriptor;
struct HudElementLayout;
struct HudInFlightMessageRecord;
struct HudPanelSpriteFileInfo;
struct HudRadarBlipPoint;
struct ImageQuantizerNode;
struct ImageQuantizerPaletteEntry;
struct ImageResource;
struct InputFrame;
struct InventorNodeDef;
struct JoystickCalibration;
struct JoystickEntry;
struct MeleeTournamentSequenceState;
struct MeleeTournamentTeamStandings;
struct MemoryHandleTableState;
struct MeshDescriptor;
struct MissionClock;
struct MissionFgRuntimeStats;
struct MissionFlightGroup;
struct MissionFlightRuntimeState;
struct MissionHeader;
struct MissionListEntry;
struct MissionMessage;
struct MissionOrder;
struct MissionSetupPlayerAssignments;
struct MissionTrigger;
struct MissionTriggerPair;
struct MobileObject;
struct MobileObjectCharData;
struct MobileObjectLinkIndices;
struct MobileObjectProximityList;
struct ModelDef;
struct ModelHangarPoints;
struct ModelLocalPoint;
struct ModelMeshObjectTypeCache;
struct ModelPreviewCraftPosition;
struct ModelTextureDefaultTexture;
struct ModelTextureDefaultTextureData;
struct ObjectTypeInfo;
struct ModelWeaponHardpoint;
struct MovieDirtyRect;
struct MovieMultiplayerSyncPlayer;
struct MoviePlaybackParams;
struct MpRosterEntry;
struct MusicCdTrackCache;
struct NetPiggybackPayload;
struct NetPlayerConnectionStats;
struct NetPlayerInfo;
struct NetQueuedPacket;
struct NetReliablePeerSlot;
struct NetSessionEnumEntry;
struct NetSessionScratchPacket;
struct ObjectPointLight;
struct ObjectRecord;
struct ObjectSlotRange;
struct OptHardpoint;
struct OptLegacyFaceDataV0;
struct OptLegacyFacePayload;
struct OptLegacyFacePayloadV0;
struct OptLegacyFaceRecordV0;
struct OptLegacyFaceStorage;
struct OptLegacyFaceStorageV0;
struct OptNode;
struct OptPackedFaceData;
struct OptPackedFaceNode;
struct OptPackedFaceRecord;
struct OptTexCoord;
struct OptTextureData;
struct OptVector;
struct OptimizedPolyObject;
struct PaiContext;
struct PaiPlanRecord;
struct PaiPlanTokenDef;
struct PerMissionKills;
struct PilotBattle;
struct PilotCampaign;
struct PilotCampaignMission;
struct PilotData;
struct PilotDataSelection;
struct PilotFaction;
struct PilotMission;
struct PilotMultiplayerBattle;
struct PilotMultiplayerMission;
struct PilotMultiplayerTournament;
struct PilotNetworkPlayer;
struct PilotStats;
struct PilotTeam;
struct PilotTournament;
struct PlayerData;
struct PlayerFlightTransientTimers;
struct PlayerHyperspaceRuntime;
struct PlayerMissionRuntimeStats;
struct PlayerNetworkRuntimeTail;
struct PlayerSavedCraftSettings;
struct PlayerViewState;
struct ProjVertex;
struct RadarEllipseClampLimit;
struct RemotePlayerRenderSample;
struct RemotePlayerSavedSimPose;
struct RenderClipVertex;
struct RenderObjectListEntry;
struct RgbTriplet;
struct SceneBillboardQueueEntry;
struct SceneEdge;
struct SceneFace;
struct SceneMesh;
struct SceneSpan;
struct SessionPlayerInfo;
struct ShipListEntry;
struct SoundEffectDef;
struct SoundQueueEntry;
struct Std3DDevice;
struct Std3DDeviceCaps;
struct Std3DDeviceDesc;
struct Std3DErrorStringEntry;
struct Std3DRasterInfo;
struct Std3DRenderTargetDesc;
struct Std3DRenderTri;
struct Std3DSurfaceState;
struct Std3DTexCacheNode;
struct Std3DTexFmt;
struct Std3DVBuffer;
struct Std3DViewportRect;
struct Std3DZBufferSurfaceBlock;
struct Std3DZBufferTarget;
struct Team;
struct TechLibrarySpecText;
struct TieRadioMessage;
struct TurretTargetState;
typedef DSWaveFormat WAVEFORMATEX;
struct WarheadGuidanceState;
struct XvtFlightGroup;
struct XvtV10FlightGroupText;
struct XvtV10MissionHeader;

#ifdef __cplusplus
}
#endif

#endif
