#ifndef XVT_XVT_TYPEDEFS_H
#define XVT_XVT_TYPEDEFS_H

#include "aeron/compat/dplay.h"
#include "aeron/compat/dsound.h"

/* Forward typedefs for every structure recovered from the
 * IDB. The defining module header declares the layout; pointer
 * references only need these names. Generated with the skeleton;
 * keep in sync with the IDB local types. */

#ifdef __cplusplus
extern "C" {
#endif

struct active_sound_instance;
struct ai_controller;
struct ai_flight_state;
struct ai_order_progress;
struct battle_continuation;
struct battle_sequence_state;
struct bitmap_font;
struct briefing_map_s16_pair;
struct cd_audio_track_cache;
struct campaign_award_sprite_entry;
struct campaign_continuation;
struct campaign_sequence_state;
struct color_info;
struct craft_damage_stats;
struct craft_data;
struct craft_laser_state;
struct craft_tech_stats;
struct craft_weapon_slot;
struct craft_weapon_stats;
struct cutscene_entry;
/* Original Windows spellings for Aeron's shared DirectSound ABI types. */
typedef DSBufferCaps DSBCAPS;
typedef DSBufferDesc DSBUFFERDESC;
typedef DSoundDeviceCaps DSCAPS;
struct direct_sound_buffer_set;
struct eai_struct;
struct e_cond_struct;
struct efg_struct;
struct e_mission_goal;
struct e_mission_struct;
struct face_record;
struct face_texture_gradients;
struct flight_radar_marker_offset;
struct flight_global_countdown_timers;
struct flight_group_goal;
struct flight_input_frame_record;
struct flight_launch_args;
struct flight_mission_state;
struct flight_net_input_batch_packet;
struct flight_net_scratch_packet;
struct flight_net_world_state_chunk_packet;
struct flight_sw_marker_offset;
struct flight_sw_rot_sprite_coeff_state;
struct flight_sw_rot_sprite_edge_point;
struct flight_sw_rot_sprite_scale_state;
struct flight_sw_rot_sprite_span_run;
struct flight_viewport_save_state;
struct front_image_resource_record;
struct front_image_rle_row_buffer;
struct frontend_briefing_script;
struct frontend_file_list;
struct frontend_file_list_node;
struct frontend_mission;
struct frontend_mission_header;
struct frontend_net_packet_scratch;
struct frontend_net_session_entry;
struct frontend_screen_state;
struct frontend_sound_buffer_record;
struct frontend_sound_voice;
struct game_config;
struct global_goal;
struct hud_beam_segment_offset;
struct hud_cockpit_resource;
struct hud_cockpit_resource_descriptor;
struct hud_element_layout;
struct hud_in_flight_message_record;
struct hud_panel_sprite_file_info;
struct hud_radar_blip_point;
struct image_quantizer_node;
struct image_quantizer_palette_entry;
struct image_resource;
struct input_frame;
struct joystick_calibration;
struct joystick_entry;
struct melee_tournament_sequence_state;
struct melee_tournament_team_standings;
struct memory_handle_table_state;
struct mesh_descriptor;
struct mission_clock;
struct mission_fg_runtime_stats;
struct mission_flight_group;
struct mission_flight_runtime_state;
struct mission_header;
struct mission_list_entry;
struct mission_message;
struct mission_order;
struct mission_setup_player_assignments;
struct mission_trigger;
struct mission_trigger_pair;
struct mobile_object;
struct mobile_object_char_data;
struct mobile_object_link_indices;
struct mobile_object_proximity_list;
struct model_def;
struct model_hangar_points;
struct model_local_point;
struct model_mesh_object_type_cache;
struct model_preview_craft_position;
struct model_texture_default_texture;
struct model_texture_default_texture_data;
struct object_type_info;
struct model_weapon_hardpoint;
struct movie_dirty_rect;
struct movie_multiplayer_sync_player;
struct movie_playback_params;
struct mp_roster_entry;
struct music_cd_track_cache;
struct net_piggyback_payload;
struct net_player_connection_stats;
struct net_player_info;
struct net_queued_packet;
struct net_reliable_peer_slot;
struct net_session_enum_entry;
struct net_session_scratch_packet;
struct object_point_light;
struct object_record;
struct object_slot_range;
struct opt_hardpoint;
struct opt_legacy_face_data_v0;
struct opt_legacy_face_payload;
struct opt_legacy_face_payload_v0;
struct opt_legacy_face_record_v0;
struct opt_legacy_face_storage;
struct opt_legacy_face_storage_v0;
struct opt_node;
struct opt_packed_face_data;
struct opt_packed_face_record;
struct opt_tex_coord;
struct opt_texture_data;
struct opt_vector;
struct optimized_poly_object;
struct pai_context;
struct pai_plan_record;
struct pai_plan_token_def;
struct per_mission_kills;
struct pilot_battle;
struct pilot_campaign;
struct pilot_campaign_mission;
struct pilot_data;
struct pilot_data_selection;
struct pilot_faction;
struct pilot_mission;
struct pilot_multiplayer_battle;
struct pilot_multiplayer_mission;
struct pilot_multiplayer_tournament;
struct pilot_network_player;
struct pilot_stats;
struct pilot_team;
struct pilot_tournament;
struct player_data;
struct player_flight_transient_timers;
struct player_hyperspace_runtime;
struct player_mission_runtime_stats;
struct player_network_runtime_tail;
struct player_saved_craft_settings;
struct player_view_state;
struct proj_vertex;
struct radar_ellipse_clamp_limit;
struct remote_player_render_sample;
struct remote_player_saved_sim_pose;
struct render_clip_vertex;
struct render_object_list_entry;
struct rgb_triplet;
struct scene_billboard_queue_entry;
struct scene_edge;
struct scene_face;
struct scene_mesh;
struct scene_span;
struct session_player_info;
struct ship_list_entry;
struct sound_effect_def;
struct sound_queue_entry;
struct std3d_device;
struct std3d_device_caps;
struct std3d_device_desc;
struct std3d_error_string_entry;
struct std3d_raster_info;
struct std3d_render_target_desc;
struct std3d_render_tri;
struct std3d_surface_state;
struct std3d_tex_cache_node;
struct std3d_tex_fmt;
struct std3dv_buffer;
struct std3d_viewport_rect;
struct std3dz_buffer_surface_block;
struct std3dz_buffer_target;
struct team;
struct tech_library_spec_text;
struct tie_radio_message;
struct turret_target_state;
typedef DSWaveFormat WAVEFORMATEX;
struct warhead_guidance_state;
struct xvt_flight_group;
struct xvt_v10_flight_group_text;
struct xvt_v10_mission_header;

#ifdef __cplusplus
}
#endif

#endif
