#ifndef XVT_RUNTIME_MISSION_DIALOGS_H
#define XVT_RUNTIME_MISSION_DIALOGS_H

#ifdef __cplusplus
extern "C" {
#endif

typedef enum XvtMissionDialogAction {
	XVT_MISSION_NOTICE,
	XVT_MISSION_SETUP_CANCELLED,
	XVT_MISSION_SETUP_BOOTED,
	XVT_MISSION_TEAM_CANCELLED,
	XVT_MISSION_ASSIGNMENT_CANCELLED,
	XVT_MISSION_BRIEFING_CANCELLED,
	XVT_MISSION_SETUP_HOST_LEAVE,
	XVT_MISSION_CLIENT_LEAVE,
	XVT_MISSION_TEAM_CLIENT_LEAVE,
	XVT_MISSION_TEAM_PREVIOUS,
	XVT_MISSION_HOST_RESTART,
	XVT_MISSION_SOLO_BACK_TO_SETUP,
	XVT_MISSION_SOLO_BACK_TO_TEAMS,
	XVT_MISSION_DEBRIEF_CLIENT_LEAVE,
	XVT_MISSION_DEBRIEF_HOST_ABORT,
	XVT_MISSION_DEBRIEF_SOLO_ABORT,
	XVT_MISSION_DEBRIEF_SOLO_ABORT_CLEAR_ROSTER
} XvtMissionDialogAction;

int XvtMissionDialogs_Resume(int result, int action);

#ifdef __cplusplus
}
#endif

#endif
