#include "xvt_runtime/snapshot/records.h"

#include <stddef.h>
#include <string.h>

typedef struct XvtSnapshotField {
	size_t nativeOffset;
	size_t recordOffset;
	size_t size;
} XvtSnapshotField;

/* Copy declared fields only: native padding never enters a snapshot or checksum. */
static void XvtSnapshot_CopyFields(void* record, void* live, const XvtSnapshotField* fields, size_t count,
								   int restore) {
	for (size_t i = 0; i < count; ++i) {
		void* disk = (uint8_t*)record + fields[i].recordOffset;
		void* native = (uint8_t*)live + fields[i].nativeOffset;
		if (restore)
			memcpy(native, disk, fields[i].size);
		else
			memcpy(disk, native, fields[i].size);
	}
}

static const XvtSnapshotField g_ObjectRecordFields[] = {
	{ offsetof(ObjectRecord, objectSignature), offsetof(XvtSnapshotObjectRecord, objectSignature),
	  sizeof(((XvtSnapshotObjectRecord*)0)->objectSignature) },
	{ offsetof(ObjectRecord, genusId), offsetof(XvtSnapshotObjectRecord, genusId),
	  sizeof(((XvtSnapshotObjectRecord*)0)->genusId) },
	{ offsetof(ObjectRecord, objectType), offsetof(XvtSnapshotObjectRecord, objectType),
	  sizeof(((XvtSnapshotObjectRecord*)0)->objectType) },
	{ offsetof(ObjectRecord, world_x), offsetof(XvtSnapshotObjectRecord, world_x),
	  sizeof(((XvtSnapshotObjectRecord*)0)->world_x) },
	{ offsetof(ObjectRecord, world_y), offsetof(XvtSnapshotObjectRecord, world_y),
	  sizeof(((XvtSnapshotObjectRecord*)0)->world_y) },
	{ offsetof(ObjectRecord, world_z), offsetof(XvtSnapshotObjectRecord, world_z),
	  sizeof(((XvtSnapshotObjectRecord*)0)->world_z) },
	{ offsetof(ObjectRecord, yaw), offsetof(XvtSnapshotObjectRecord, yaw),
	  sizeof(((XvtSnapshotObjectRecord*)0)->yaw) },
	{ offsetof(ObjectRecord, pitch), offsetof(XvtSnapshotObjectRecord, pitch),
	  sizeof(((XvtSnapshotObjectRecord*)0)->pitch) },
	{ offsetof(ObjectRecord, roll), offsetof(XvtSnapshotObjectRecord, roll),
	  sizeof(((XvtSnapshotObjectRecord*)0)->roll) },
	{ offsetof(ObjectRecord, flightGroupIdx), offsetof(XvtSnapshotObjectRecord, flightGroupIdx),
	  sizeof(((XvtSnapshotObjectRecord*)0)->flightGroupIdx) },
	{ offsetof(ObjectRecord, typeSpecificWord), offsetof(XvtSnapshotObjectRecord, typeSpecificWord),
	  sizeof(((XvtSnapshotObjectRecord*)0)->typeSpecificWord) },
	{ offsetof(ObjectRecord, typeSpecificByte), offsetof(XvtSnapshotObjectRecord, typeSpecificByte),
	  sizeof(((XvtSnapshotObjectRecord*)0)->typeSpecificByte) },
	{ offsetof(ObjectRecord, playerOwnerIdx), offsetof(XvtSnapshotObjectRecord, playerOwnerIdx),
	  sizeof(((XvtSnapshotObjectRecord*)0)->playerOwnerIdx) },
};

void XvtSnapshot_EncodeObjectRecord(XvtSnapshotObjectRecord* record, const ObjectRecord* live) {
	XvtSnapshot_CopyFields((void*)record, (void*)live, g_ObjectRecordFields,
						   sizeof(g_ObjectRecordFields) / sizeof(g_ObjectRecordFields[0]), 0);
	record->mobj =
		live->mobj ? (uint32_t)((live->mobj - g_mobileObjectPoolBase) * sizeof(XvtSnapshotMobileObject) + 1)
				   : 0;
}

void XvtSnapshot_DecodeObjectRecord(ObjectRecord* live, const XvtSnapshotObjectRecord* record) {
	XvtSnapshot_CopyFields((void*)record, (void*)live, g_ObjectRecordFields,
						   sizeof(g_ObjectRecordFields) / sizeof(g_ObjectRecordFields[0]), 1);
	live->mobj =
		record->mobj ? &g_mobileObjectPoolBase[(record->mobj - 1) / sizeof(XvtSnapshotMobileObject)] : NULL;
}

static const XvtSnapshotField g_MobileObjectFields[] = {
	{ offsetof(MobileObject, family), offsetof(XvtSnapshotMobileObject, family),
	  sizeof(((XvtSnapshotMobileObject*)0)->family) },
	{ offsetof(MobileObject, effectSize), offsetof(XvtSnapshotMobileObject, effectSize),
	  sizeof(((XvtSnapshotMobileObject*)0)->effectSize) },
	{ offsetof(MobileObject, simStateTimestamp), offsetof(XvtSnapshotMobileObject, simStateTimestamp),
	  sizeof(((XvtSnapshotMobileObject*)0)->simStateTimestamp) },
	{ offsetof(MobileObject, prevWorldX), offsetof(XvtSnapshotMobileObject, prevWorldX),
	  sizeof(((XvtSnapshotMobileObject*)0)->prevWorldX) },
	{ offsetof(MobileObject, prevWorldY), offsetof(XvtSnapshotMobileObject, prevWorldY),
	  sizeof(((XvtSnapshotMobileObject*)0)->prevWorldY) },
	{ offsetof(MobileObject, prevWorldZ), offsetof(XvtSnapshotMobileObject, prevWorldZ),
	  sizeof(((XvtSnapshotMobileObject*)0)->prevWorldZ) },
	{ offsetof(MobileObject, proximityList.count), offsetof(XvtSnapshotMobileObject, proximityList.count),
	  sizeof(((XvtSnapshotMobileObject*)0)->proximityList.count) },
	{ offsetof(MobileObject, proximityList.contactTicks),
	  offsetof(XvtSnapshotMobileObject, proximityList.contactTicks),
	  sizeof(((XvtSnapshotMobileObject*)0)->proximityList.contactTicks) },
	{ offsetof(MobileObject, proximityList.objIdx), offsetof(XvtSnapshotMobileObject, proximityList.objIdx),
	  sizeof(((XvtSnapshotMobileObject*)0)->proximityList.objIdx) },
	{ offsetof(MobileObject, proximityList.rebuildTicks),
	  offsetof(XvtSnapshotMobileObject, proximityList.rebuildTicks),
	  sizeof(((XvtSnapshotMobileObject*)0)->proximityList.rebuildTicks) },
	{ offsetof(MobileObject, rollImpulseRate), offsetof(XvtSnapshotMobileObject, rollImpulseRate),
	  sizeof(((XvtSnapshotMobileObject*)0)->rollImpulseRate) },
	{ offsetof(MobileObject, speed), offsetof(XvtSnapshotMobileObject, speed),
	  sizeof(((XvtSnapshotMobileObject*)0)->speed) },
	{ offsetof(MobileObject, speedRemainder), offsetof(XvtSnapshotMobileObject, speedRemainder),
	  sizeof(((XvtSnapshotMobileObject*)0)->speedRemainder) },
	{ offsetof(MobileObject, damageAmount), offsetof(XvtSnapshotMobileObject, damageAmount),
	  sizeof(((XvtSnapshotMobileObject*)0)->damageAmount) },
	{ offsetof(MobileObject, lifetimeTimer), offsetof(XvtSnapshotMobileObject, lifetimeTimer),
	  sizeof(((XvtSnapshotMobileObject*)0)->lifetimeTimer) },
	{ offsetof(MobileObject, secondsAlive), offsetof(XvtSnapshotMobileObject, secondsAlive),
	  sizeof(((XvtSnapshotMobileObject*)0)->secondsAlive) },
	{ offsetof(MobileObject, sourceObjIdx), offsetof(XvtSnapshotMobileObject, sourceObjIdx),
	  sizeof(((XvtSnapshotMobileObject*)0)->sourceObjIdx) },
	{ offsetof(MobileObject, sourceObjectType), offsetof(XvtSnapshotMobileObject, sourceObjectType),
	  sizeof(((XvtSnapshotMobileObject*)0)->sourceObjectType) },
	{ offsetof(MobileObject, iff), offsetof(XvtSnapshotMobileObject, iff),
	  sizeof(((XvtSnapshotMobileObject*)0)->iff) },
	{ offsetof(MobileObject, team), offsetof(XvtSnapshotMobileObject, team),
	  sizeof(((XvtSnapshotMobileObject*)0)->team) },
	{ offsetof(MobileObject, nodeSwitchIndex), offsetof(XvtSnapshotMobileObject, nodeSwitchIndex),
	  sizeof(((XvtSnapshotMobileObject*)0)->nodeSwitchIndex) },
	{ offsetof(MobileObject, moveVectorDirty), offsetof(XvtSnapshotMobileObject, moveVectorDirty),
	  sizeof(((XvtSnapshotMobileObject*)0)->moveVectorDirty) },
	{ offsetof(MobileObject, moveX), offsetof(XvtSnapshotMobileObject, moveX),
	  sizeof(((XvtSnapshotMobileObject*)0)->moveX) },
	{ offsetof(MobileObject, moveY), offsetof(XvtSnapshotMobileObject, moveY),
	  sizeof(((XvtSnapshotMobileObject*)0)->moveY) },
	{ offsetof(MobileObject, moveZ), offsetof(XvtSnapshotMobileObject, moveZ),
	  sizeof(((XvtSnapshotMobileObject*)0)->moveZ) },
	{ offsetof(MobileObject, orientMatrixDirty), offsetof(XvtSnapshotMobileObject, orientMatrixDirty),
	  sizeof(((XvtSnapshotMobileObject*)0)->orientMatrixDirty) },
	{ offsetof(MobileObject, cachedFwdX), offsetof(XvtSnapshotMobileObject, cachedFwdX),
	  sizeof(((XvtSnapshotMobileObject*)0)->cachedFwdX) },
	{ offsetof(MobileObject, cachedFwdY), offsetof(XvtSnapshotMobileObject, cachedFwdY),
	  sizeof(((XvtSnapshotMobileObject*)0)->cachedFwdY) },
	{ offsetof(MobileObject, cachedFwdZ), offsetof(XvtSnapshotMobileObject, cachedFwdZ),
	  sizeof(((XvtSnapshotMobileObject*)0)->cachedFwdZ) },
	{ offsetof(MobileObject, cachedSideX), offsetof(XvtSnapshotMobileObject, cachedSideX),
	  sizeof(((XvtSnapshotMobileObject*)0)->cachedSideX) },
	{ offsetof(MobileObject, cachedSideY), offsetof(XvtSnapshotMobileObject, cachedSideY),
	  sizeof(((XvtSnapshotMobileObject*)0)->cachedSideY) },
	{ offsetof(MobileObject, cachedSideZ), offsetof(XvtSnapshotMobileObject, cachedSideZ),
	  sizeof(((XvtSnapshotMobileObject*)0)->cachedSideZ) },
	{ offsetof(MobileObject, cachedUpX), offsetof(XvtSnapshotMobileObject, cachedUpX),
	  sizeof(((XvtSnapshotMobileObject*)0)->cachedUpX) },
	{ offsetof(MobileObject, cachedUpY), offsetof(XvtSnapshotMobileObject, cachedUpY),
	  sizeof(((XvtSnapshotMobileObject*)0)->cachedUpY) },
	{ offsetof(MobileObject, cachedUpZ), offsetof(XvtSnapshotMobileObject, cachedUpZ),
	  sizeof(((XvtSnapshotMobileObject*)0)->cachedUpZ) },
};

void XvtSnapshot_EncodeMobileObject(XvtSnapshotMobileObject* record, const MobileObject* live) {
	XvtSnapshot_CopyFields((void*)record, (void*)live, g_MobileObjectFields,
						   sizeof(g_MobileObjectFields) / sizeof(g_MobileObjectFields[0]), 0);
	record->pWarheadGuidance = live->pWarheadGuidance
								   ? (uint32_t)((live->pWarheadGuidance - g_projectileGuidanceStates) *
													sizeof(WarheadGuidanceState) +
												1)
								   : 0;
	record->pCraft = live->pCraft
						 ? (uint32_t)((live->pCraft - g_craftDataPoolBase) * sizeof(XvtSnapshotCraftData) + 1)
						 : 0;
	record->pCharData = live->pCharData ? (uint32_t)((live->pCharData - g_mobileObjectCharDataPool) *
														 sizeof(XvtSnapshotMobileObjectCharData) +
													 1)
										: 0;
}

void XvtSnapshot_DecodeMobileObject(MobileObject* live, const XvtSnapshotMobileObject* record) {
	XvtSnapshot_CopyFields((void*)record, (void*)live, g_MobileObjectFields,
						   sizeof(g_MobileObjectFields) / sizeof(g_MobileObjectFields[0]), 1);
	live->pWarheadGuidance =
		record->pWarheadGuidance
			? &g_projectileGuidanceStates[(record->pWarheadGuidance - 1) / sizeof(WarheadGuidanceState)]
			: NULL;
	live->pCraft =
		record->pCraft ? &g_craftDataPoolBase[(record->pCraft - 1) / sizeof(XvtSnapshotCraftData)] : NULL;
	live->pCharData =
		record->pCharData
			? &g_mobileObjectCharDataPool[(record->pCharData - 1) / sizeof(XvtSnapshotMobileObjectCharData)]
			: NULL;
}

static const XvtSnapshotField g_CraftDataFields[] = {
	{ offsetof(CraftData, craftIndexInGroup), offsetof(XvtSnapshotCraftData, craftIndexInGroup),
	  sizeof(((XvtSnapshotCraftData*)0)->craftIndexInGroup) },
	{ offsetof(CraftData, modelIndex), offsetof(XvtSnapshotCraftData, modelIndex),
	  sizeof(((XvtSnapshotCraftData*)0)->modelIndex) },
	{ offsetof(CraftData, leader_obj_idx), offsetof(XvtSnapshotCraftData, leader_obj_idx),
	  sizeof(((XvtSnapshotCraftData*)0)->leader_obj_idx) },
	{ offsetof(CraftData, field_006), offsetof(XvtSnapshotCraftData, field_006),
	  sizeof(((XvtSnapshotCraftData*)0)->field_006) },
	{ offsetof(CraftData, objectKind), offsetof(XvtSnapshotCraftData, objectKind),
	  sizeof(((XvtSnapshotCraftData*)0)->objectKind) },
	{ offsetof(CraftData, missionAccountingDone), offsetof(XvtSnapshotCraftData, missionAccountingDone),
	  sizeof(((XvtSnapshotCraftData*)0)->missionAccountingDone) },
	{ offsetof(CraftData, aiSkill), offsetof(XvtSnapshotCraftData, aiSkill),
	  sizeof(((XvtSnapshotCraftData*)0)->aiSkill) },
	{ offsetof(CraftData, field_00B), offsetof(XvtSnapshotCraftData, field_00B),
	  sizeof(((XvtSnapshotCraftData*)0)->field_00B) },
	{ offsetof(CraftData, pitch), offsetof(XvtSnapshotCraftData, pitch),
	  sizeof(((XvtSnapshotCraftData*)0)->pitch) },
	{ offsetof(CraftData, yaw), offsetof(XvtSnapshotCraftData, yaw),
	  sizeof(((XvtSnapshotCraftData*)0)->yaw) },
	{ offsetof(CraftData, breakupPitchRate), offsetof(XvtSnapshotCraftData, breakupPitchRate),
	  sizeof(((XvtSnapshotCraftData*)0)->breakupPitchRate) },
	{ offsetof(CraftData, breakupYawRate), offsetof(XvtSnapshotCraftData, breakupYawRate),
	  sizeof(((XvtSnapshotCraftData*)0)->breakupYawRate) },
	{ offsetof(CraftData, beamEffectAccum), offsetof(XvtSnapshotCraftData, beamEffectAccum),
	  sizeof(((XvtSnapshotCraftData*)0)->beamEffectAccum) },
	{ offsetof(CraftData, sFoilState), offsetof(XvtSnapshotCraftData, sFoilState),
	  sizeof(((XvtSnapshotCraftData*)0)->sFoilState) },
	{ offsetof(CraftData, aiController.currentOrderSlot),
	  offsetof(XvtSnapshotCraftData, aiController.currentOrderSlot),
	  sizeof(((XvtSnapshotCraftData*)0)->aiController.currentOrderSlot) },
	{ offsetof(CraftData, aiController.orderProgress),
	  offsetof(XvtSnapshotCraftData, aiController.orderProgress),
	  sizeof(((XvtSnapshotCraftData*)0)->aiController.orderProgress) },
	{ offsetof(CraftData, aiController.skippedToOrder4),
	  offsetof(XvtSnapshotCraftData, aiController.skippedToOrder4),
	  sizeof(((XvtSnapshotCraftData*)0)->aiController.skippedToOrder4) },
	{ offsetof(CraftData, aiController.pendingPlanId),
	  offsetof(XvtSnapshotCraftData, aiController.pendingPlanId),
	  sizeof(((XvtSnapshotCraftData*)0)->aiController.pendingPlanId) },
	{ offsetof(CraftData, aiController.currentPlanId),
	  offsetof(XvtSnapshotCraftData, aiController.currentPlanId),
	  sizeof(((XvtSnapshotCraftData*)0)->aiController.currentPlanId) },
	{ offsetof(CraftData, aiController.waypointIndex),
	  offsetof(XvtSnapshotCraftData, aiController.waypointIndex),
	  sizeof(((XvtSnapshotCraftData*)0)->aiController.waypointIndex) },
	{ offsetof(CraftData, aiController.savedPlanId), offsetof(XvtSnapshotCraftData, aiController.savedPlanId),
	  sizeof(((XvtSnapshotCraftData*)0)->aiController.savedPlanId) },
	{ offsetof(CraftData, aiController.thinkInterval),
	  offsetof(XvtSnapshotCraftData, aiController.thinkInterval),
	  sizeof(((XvtSnapshotCraftData*)0)->aiController.thinkInterval) },
	{ offsetof(CraftData, aiController.thinkTimer), offsetof(XvtSnapshotCraftData, aiController.thinkTimer),
	  sizeof(((XvtSnapshotCraftData*)0)->aiController.thinkTimer) },
	{ offsetof(CraftData, aiController.savedRandSeed),
	  offsetof(XvtSnapshotCraftData, aiController.savedRandSeed),
	  sizeof(((XvtSnapshotCraftData*)0)->aiController.savedRandSeed) },
	{ offsetof(CraftData, aiController.targetObjIdx),
	  offsetof(XvtSnapshotCraftData, aiController.targetObjIdx),
	  sizeof(((XvtSnapshotCraftData*)0)->aiController.targetObjIdx) },
	{ offsetof(CraftData, aiController.targetSignature),
	  offsetof(XvtSnapshotCraftData, aiController.targetSignature),
	  sizeof(((XvtSnapshotCraftData*)0)->aiController.targetSignature) },
	{ offsetof(CraftData, aiController.targetComponent),
	  offsetof(XvtSnapshotCraftData, aiController.targetComponent),
	  sizeof(((XvtSnapshotCraftData*)0)->aiController.targetComponent) },
	{ offsetof(CraftData, aiController.hasLiveTarget),
	  offsetof(XvtSnapshotCraftData, aiController.hasLiveTarget),
	  sizeof(((XvtSnapshotCraftData*)0)->aiController.hasLiveTarget) },
	{ offsetof(CraftData, aiController.aimPointX), offsetof(XvtSnapshotCraftData, aiController.aimPointX),
	  sizeof(((XvtSnapshotCraftData*)0)->aiController.aimPointX) },
	{ offsetof(CraftData, aiController.aimPointY), offsetof(XvtSnapshotCraftData, aiController.aimPointY),
	  sizeof(((XvtSnapshotCraftData*)0)->aiController.aimPointY) },
	{ offsetof(CraftData, aiController.aimPointZ), offsetof(XvtSnapshotCraftData, aiController.aimPointZ),
	  sizeof(((XvtSnapshotCraftData*)0)->aiController.aimPointZ) },
	{ offsetof(CraftData, aiController.candidateTargetIdx),
	  offsetof(XvtSnapshotCraftData, aiController.candidateTargetIdx),
	  sizeof(((XvtSnapshotCraftData*)0)->aiController.candidateTargetIdx) },
	{ offsetof(CraftData, aiController.escortTargetFG),
	  offsetof(XvtSnapshotCraftData, aiController.escortTargetFG),
	  sizeof(((XvtSnapshotCraftData*)0)->aiController.escortTargetFG) },
	{ offsetof(CraftData, aiController.targetZAngle),
	  offsetof(XvtSnapshotCraftData, aiController.targetZAngle),
	  sizeof(((XvtSnapshotCraftData*)0)->aiController.targetZAngle) },
	{ offsetof(CraftData, aiController.targetRoll), offsetof(XvtSnapshotCraftData, aiController.targetRoll),
	  sizeof(((XvtSnapshotCraftData*)0)->aiController.targetRoll) },
	{ offsetof(CraftData, aiController.targetXYAngle),
	  offsetof(XvtSnapshotCraftData, aiController.targetXYAngle),
	  sizeof(((XvtSnapshotCraftData*)0)->aiController.targetXYAngle) },
	{ offsetof(CraftData, aiController.maneuverMode),
	  offsetof(XvtSnapshotCraftData, aiController.maneuverMode),
	  sizeof(((XvtSnapshotCraftData*)0)->aiController.maneuverMode) },
	{ offsetof(CraftData, aiController.maneuverPhase),
	  offsetof(XvtSnapshotCraftData, aiController.maneuverPhase),
	  sizeof(((XvtSnapshotCraftData*)0)->aiController.maneuverPhase) },
	{ offsetof(CraftData, aiController.maneuverTimer),
	  offsetof(XvtSnapshotCraftData, aiController.maneuverTimer),
	  sizeof(((XvtSnapshotCraftData*)0)->aiController.maneuverTimer) },
	{ offsetof(CraftData, aiController.secondaryManeuverTimer),
	  offsetof(XvtSnapshotCraftData, aiController.secondaryManeuverTimer),
	  sizeof(((XvtSnapshotCraftData*)0)->aiController.secondaryManeuverTimer) },
	{ offsetof(CraftData, carriedObjectIndex), offsetof(XvtSnapshotCraftData, carriedObjectIndex),
	  sizeof(((XvtSnapshotCraftData*)0)->carriedObjectIndex) },
	{ offsetof(CraftData, carrierObjIdx), offsetof(XvtSnapshotCraftData, carrierObjIdx),
	  sizeof(((XvtSnapshotCraftData*)0)->carrierObjIdx) },
	{ offsetof(CraftData, lastAttackerObjIdx), offsetof(XvtSnapshotCraftData, lastAttackerObjIdx),
	  sizeof(((XvtSnapshotCraftData*)0)->lastAttackerObjIdx) },
	{ offsetof(CraftData, lastHitMissionSecond), offsetof(XvtSnapshotCraftData, lastHitMissionSecond),
	  sizeof(((XvtSnapshotCraftData*)0)->lastHitMissionSecond) },
	{ offsetof(CraftData, aiFlight.threatObjIdx), offsetof(XvtSnapshotCraftData, aiFlight.threatObjIdx),
	  sizeof(((XvtSnapshotCraftData*)0)->aiFlight.threatObjIdx) },
	{ offsetof(CraftData, aiFlight.impactObjIdx), offsetof(XvtSnapshotCraftData, aiFlight.impactObjIdx),
	  sizeof(((XvtSnapshotCraftData*)0)->aiFlight.impactObjIdx) },
	{ offsetof(CraftData, aiFlight.goHomeFlag), offsetof(XvtSnapshotCraftData, aiFlight.goHomeFlag),
	  sizeof(((XvtSnapshotCraftData*)0)->aiFlight.goHomeFlag) },
	{ offsetof(CraftData, aiFlight.missionAbortedFlag),
	  offsetof(XvtSnapshotCraftData, aiFlight.missionAbortedFlag),
	  sizeof(((XvtSnapshotCraftData*)0)->aiFlight.missionAbortedFlag) },
	{ offsetof(CraftData, aiFlight.departTimerFlag), offsetof(XvtSnapshotCraftData, aiFlight.departTimerFlag),
	  sizeof(((XvtSnapshotCraftData*)0)->aiFlight.departTimerFlag) },
	{ offsetof(CraftData, aiFlight.departClockHours),
	  offsetof(XvtSnapshotCraftData, aiFlight.departClockHours),
	  sizeof(((XvtSnapshotCraftData*)0)->aiFlight.departClockHours) },
	{ offsetof(CraftData, aiFlight.departClockMinutes),
	  offsetof(XvtSnapshotCraftData, aiFlight.departClockMinutes),
	  sizeof(((XvtSnapshotCraftData*)0)->aiFlight.departClockMinutes) },
	{ offsetof(CraftData, aiFlight.departClockSeconds),
	  offsetof(XvtSnapshotCraftData, aiFlight.departClockSeconds),
	  sizeof(((XvtSnapshotCraftData*)0)->aiFlight.departClockSeconds) },
	{ offsetof(CraftData, aiFlight.warheadsFiredThisManeuver),
	  offsetof(XvtSnapshotCraftData, aiFlight.warheadsFiredThisManeuver),
	  sizeof(((XvtSnapshotCraftData*)0)->aiFlight.warheadsFiredThisManeuver) },
	{ offsetof(CraftData, aiFlight.hitsThisManeuver),
	  offsetof(XvtSnapshotCraftData, aiFlight.hitsThisManeuver),
	  sizeof(((XvtSnapshotCraftData*)0)->aiFlight.hitsThisManeuver) },
	{ offsetof(CraftData, aiFlight.boardedAccountingDone),
	  offsetof(XvtSnapshotCraftData, aiFlight.boardedAccountingDone),
	  sizeof(((XvtSnapshotCraftData*)0)->aiFlight.boardedAccountingDone) },
	{ offsetof(CraftData, aiFlight.timesBoarded), offsetof(XvtSnapshotCraftData, aiFlight.timesBoarded),
	  sizeof(((XvtSnapshotCraftData*)0)->aiFlight.timesBoarded) },
	{ offsetof(CraftData, aiFlight.dockingAccountingDone),
	  offsetof(XvtSnapshotCraftData, aiFlight.dockingAccountingDone),
	  sizeof(((XvtSnapshotCraftData*)0)->aiFlight.dockingAccountingDone) },
	{ offsetof(CraftData, aiFlight.objSignatureCount),
	  offsetof(XvtSnapshotCraftData, aiFlight.objSignatureCount),
	  sizeof(((XvtSnapshotCraftData*)0)->aiFlight.objSignatureCount) },
	{ offsetof(CraftData, aiFlight.objSignatures), offsetof(XvtSnapshotCraftData, aiFlight.objSignatures),
	  sizeof(((XvtSnapshotCraftData*)0)->aiFlight.objSignatures) },
	{ offsetof(CraftData, aiFlight.maxSpeedCache), offsetof(XvtSnapshotCraftData, aiFlight.maxSpeedCache),
	  sizeof(((XvtSnapshotCraftData*)0)->aiFlight.maxSpeedCache) },
	{ offsetof(CraftData, aiFlight.motionScale), offsetof(XvtSnapshotCraftData, aiFlight.motionScale),
	  sizeof(((XvtSnapshotCraftData*)0)->aiFlight.motionScale) },
	{ offsetof(CraftData, aiFlight.climbState), offsetof(XvtSnapshotCraftData, aiFlight.climbState),
	  sizeof(((XvtSnapshotCraftData*)0)->aiFlight.climbState) },
	{ offsetof(CraftData, aiFlight.diveState), offsetof(XvtSnapshotCraftData, aiFlight.diveState),
	  sizeof(((XvtSnapshotCraftData*)0)->aiFlight.diveState) },
	{ offsetof(CraftData, aiFlight.pitchRate), offsetof(XvtSnapshotCraftData, aiFlight.pitchRate),
	  sizeof(((XvtSnapshotCraftData*)0)->aiFlight.pitchRate) },
	{ offsetof(CraftData, aiFlight.pitchAccel), offsetof(XvtSnapshotCraftData, aiFlight.pitchAccel),
	  sizeof(((XvtSnapshotCraftData*)0)->aiFlight.pitchAccel) },
	{ offsetof(CraftData, aiFlight.pitchState), offsetof(XvtSnapshotCraftData, aiFlight.pitchState),
	  sizeof(((XvtSnapshotCraftData*)0)->aiFlight.pitchState) },
	{ offsetof(CraftData, aiFlight.pitchThroughLoop),
	  offsetof(XvtSnapshotCraftData, aiFlight.pitchThroughLoop),
	  sizeof(((XvtSnapshotCraftData*)0)->aiFlight.pitchThroughLoop) },
	{ offsetof(CraftData, aiFlight.pitchStepScale), offsetof(XvtSnapshotCraftData, aiFlight.pitchStepScale),
	  sizeof(((XvtSnapshotCraftData*)0)->aiFlight.pitchStepScale) },
	{ offsetof(CraftData, aiFlight.rollRate), offsetof(XvtSnapshotCraftData, aiFlight.rollRate),
	  sizeof(((XvtSnapshotCraftData*)0)->aiFlight.rollRate) },
	{ offsetof(CraftData, aiFlight.rollAccel), offsetof(XvtSnapshotCraftData, aiFlight.rollAccel),
	  sizeof(((XvtSnapshotCraftData*)0)->aiFlight.rollAccel) },
	{ offsetof(CraftData, aiFlight.rollState), offsetof(XvtSnapshotCraftData, aiFlight.rollState),
	  sizeof(((XvtSnapshotCraftData*)0)->aiFlight.rollState) },
	{ offsetof(CraftData, aiFlight.rollStep), offsetof(XvtSnapshotCraftData, aiFlight.rollStep),
	  sizeof(((XvtSnapshotCraftData*)0)->aiFlight.rollStep) },
	{ offsetof(CraftData, aiFlight.turnRate), offsetof(XvtSnapshotCraftData, aiFlight.turnRate),
	  sizeof(((XvtSnapshotCraftData*)0)->aiFlight.turnRate) },
	{ offsetof(CraftData, aiFlight.turnAccel), offsetof(XvtSnapshotCraftData, aiFlight.turnAccel),
	  sizeof(((XvtSnapshotCraftData*)0)->aiFlight.turnAccel) },
	{ offsetof(CraftData, aiFlight.turnState), offsetof(XvtSnapshotCraftData, aiFlight.turnState),
	  sizeof(((XvtSnapshotCraftData*)0)->aiFlight.turnState) },
	{ offsetof(CraftData, aiFlight.turnStep), offsetof(XvtSnapshotCraftData, aiFlight.turnStep),
	  sizeof(((XvtSnapshotCraftData*)0)->aiFlight.turnStep) },
	{ offsetof(CraftData, aiFlight.formationType), offsetof(XvtSnapshotCraftData, aiFlight.formationType),
	  sizeof(((XvtSnapshotCraftData*)0)->aiFlight.formationType) },
	{ offsetof(CraftData, aiFlight.separation), offsetof(XvtSnapshotCraftData, aiFlight.separation),
	  sizeof(((XvtSnapshotCraftData*)0)->aiFlight.separation) },
	{ offsetof(CraftData, waveNumber), offsetof(XvtSnapshotCraftData, waveNumber),
	  sizeof(((XvtSnapshotCraftData*)0)->waveNumber) },
	{ offsetof(CraftData, pushAccumX), offsetof(XvtSnapshotCraftData, pushAccumX),
	  sizeof(((XvtSnapshotCraftData*)0)->pushAccumX) },
	{ offsetof(CraftData, pushAccumY), offsetof(XvtSnapshotCraftData, pushAccumY),
	  sizeof(((XvtSnapshotCraftData*)0)->pushAccumY) },
	{ offsetof(CraftData, pushAccumZ), offsetof(XvtSnapshotCraftData, pushAccumZ),
	  sizeof(((XvtSnapshotCraftData*)0)->pushAccumZ) },
	{ offsetof(CraftData, throttleSpeed), offsetof(XvtSnapshotCraftData, throttleSpeed),
	  sizeof(((XvtSnapshotCraftData*)0)->throttleSpeed) },
	{ offsetof(CraftData, engineOverdriveOff), offsetof(XvtSnapshotCraftData, engineOverdriveOff),
	  sizeof(((XvtSnapshotCraftData*)0)->engineOverdriveOff) },
	{ offsetof(CraftData, commandedSpeed), offsetof(XvtSnapshotCraftData, commandedSpeed),
	  sizeof(((XvtSnapshotCraftData*)0)->commandedSpeed) },
	{ offsetof(CraftData, hullDamage), offsetof(XvtSnapshotCraftData, hullDamage),
	  sizeof(((XvtSnapshotCraftData*)0)->hullDamage) },
	{ offsetof(CraftData, systemDamageHullThreshold),
	  offsetof(XvtSnapshotCraftData, systemDamageHullThreshold),
	  sizeof(((XvtSnapshotCraftData*)0)->systemDamageHullThreshold) },
	{ offsetof(CraftData, hullMax), offsetof(XvtSnapshotCraftData, hullMax),
	  sizeof(((XvtSnapshotCraftData*)0)->hullMax) },
	{ offsetof(CraftData, subsystemDamage), offsetof(XvtSnapshotCraftData, subsystemDamage),
	  sizeof(((XvtSnapshotCraftData*)0)->subsystemDamage) },
	{ offsetof(CraftData, damageStats.lastSystemHitTime),
	  offsetof(XvtSnapshotCraftData, damageStats.lastSystemHitTime),
	  sizeof(((XvtSnapshotCraftData*)0)->damageStats.lastSystemHitTime) },
	{ offsetof(CraftData, damageStats.damageReceivedTotal),
	  offsetof(XvtSnapshotCraftData, damageStats.damageReceivedTotal),
	  sizeof(((XvtSnapshotCraftData*)0)->damageStats.damageReceivedTotal) },
	{ offsetof(CraftData, damageStats.damageReceivedByPlayerOwnedCraft),
	  offsetof(XvtSnapshotCraftData, damageStats.damageReceivedByPlayerOwnedCraft),
	  sizeof(((XvtSnapshotCraftData*)0)->damageStats.damageReceivedByPlayerOwnedCraft) },
	{ offsetof(CraftData, damageStats.damageFromCollision),
	  offsetof(XvtSnapshotCraftData, damageStats.damageFromCollision),
	  sizeof(((XvtSnapshotCraftData*)0)->damageStats.damageFromCollision) },
	{ offsetof(CraftData, damageStats.damageFromStarship),
	  offsetof(XvtSnapshotCraftData, damageStats.damageFromStarship),
	  sizeof(((XvtSnapshotCraftData*)0)->damageStats.damageFromStarship) },
	{ offsetof(CraftData, damageStats.damageFromMine),
	  offsetof(XvtSnapshotCraftData, damageStats.damageFromMine),
	  sizeof(((XvtSnapshotCraftData*)0)->damageStats.damageFromMine) },
	{ offsetof(CraftData, damageStats.damageFromFlightGroupAmount),
	  offsetof(XvtSnapshotCraftData, damageStats.damageFromFlightGroupAmount),
	  sizeof(((XvtSnapshotCraftData*)0)->damageStats.damageFromFlightGroupAmount) },
	{ offsetof(CraftData, damageStats.damageFromPlayer),
	  offsetof(XvtSnapshotCraftData, damageStats.damageFromPlayer),
	  sizeof(((XvtSnapshotCraftData*)0)->damageStats.damageFromPlayer) },
	{ offsetof(CraftData, damageStats.damageFromAiSkill),
	  offsetof(XvtSnapshotCraftData, damageStats.damageFromAiSkill),
	  sizeof(((XvtSnapshotCraftData*)0)->damageStats.damageFromAiSkill) },
	{ offsetof(CraftData, damageStats.installedHudFeatureMask),
	  offsetof(XvtSnapshotCraftData, damageStats.installedHudFeatureMask),
	  sizeof(((XvtSnapshotCraftData*)0)->damageStats.installedHudFeatureMask) },
	{ offsetof(CraftData, damageStats.activeHudFeatureMask),
	  offsetof(XvtSnapshotCraftData, damageStats.activeHudFeatureMask),
	  sizeof(((XvtSnapshotCraftData*)0)->damageStats.activeHudFeatureMask) },
	{ offsetof(CraftData, systemFlags), offsetof(XvtSnapshotCraftData, systemFlags),
	  sizeof(((XvtSnapshotCraftData*)0)->systemFlags) },
	{ offsetof(CraftData, workingSubsystems), offsetof(XvtSnapshotCraftData, workingSubsystems),
	  sizeof(((XvtSnapshotCraftData*)0)->workingSubsystems) },
	{ offsetof(CraftData, weaponFireInhibitTimer), offsetof(XvtSnapshotCraftData, weaponFireInhibitTimer),
	  sizeof(((XvtSnapshotCraftData*)0)->weaponFireInhibitTimer) },
	{ offsetof(CraftData, unusedMissionFlag), offsetof(XvtSnapshotCraftData, unusedMissionFlag),
	  sizeof(((XvtSnapshotCraftData*)0)->unusedMissionFlag) },
	{ offsetof(CraftData, notDisabledAccountingSuppress),
	  offsetof(XvtSnapshotCraftData, notDisabledAccountingSuppress),
	  sizeof(((XvtSnapshotCraftData*)0)->notDisabledAccountingSuppress) },
	{ offsetof(CraftData, capturedByFlightGroup), offsetof(XvtSnapshotCraftData, capturedByFlightGroup),
	  sizeof(((XvtSnapshotCraftData*)0)->capturedByFlightGroup) },
	{ offsetof(CraftData, attackedByTeam), offsetof(XvtSnapshotCraftData, attackedByTeam),
	  sizeof(((XvtSnapshotCraftData*)0)->attackedByTeam) },
	{ offsetof(CraftData, identifiedOrderByTeam), offsetof(XvtSnapshotCraftData, identifiedOrderByTeam),
	  sizeof(((XvtSnapshotCraftData*)0)->identifiedOrderByTeam) },
	{ offsetof(CraftData, boardingState), offsetof(XvtSnapshotCraftData, boardingState),
	  sizeof(((XvtSnapshotCraftData*)0)->boardingState) },
	{ offsetof(CraftData, specialCargoName), offsetof(XvtSnapshotCraftData, specialCargoName),
	  sizeof(((XvtSnapshotCraftData*)0)->specialCargoName) },
	{ offsetof(CraftData, shieldEnergy), offsetof(XvtSnapshotCraftData, shieldEnergy),
	  sizeof(((XvtSnapshotCraftData*)0)->shieldEnergy) },
	{ offsetof(CraftData, shieldRechargeLevel), offsetof(XvtSnapshotCraftData, shieldRechargeLevel),
	  sizeof(((XvtSnapshotCraftData*)0)->shieldRechargeLevel) },
	{ offsetof(CraftData, shieldDistribMode), offsetof(XvtSnapshotCraftData, shieldDistribMode),
	  sizeof(((XvtSnapshotCraftData*)0)->shieldDistribMode) },
	{ offsetof(CraftData, cannonGroupCount), offsetof(XvtSnapshotCraftData, cannonGroupCount),
	  sizeof(((XvtSnapshotCraftData*)0)->cannonGroupCount) },
	{ offsetof(CraftData, laserRechargeLevel), offsetof(XvtSnapshotCraftData, laserRechargeLevel),
	  sizeof(((XvtSnapshotCraftData*)0)->laserRechargeLevel) },
	{ offsetof(CraftData, laserSlotCount), offsetof(XvtSnapshotCraftData, laserSlotCount),
	  sizeof(((XvtSnapshotCraftData*)0)->laserSlotCount) },
	{ offsetof(CraftData, laserState), offsetof(XvtSnapshotCraftData, laserState),
	  sizeof(((XvtSnapshotCraftData*)0)->laserState) },
	{ offsetof(CraftData, warheadLauncherCount), offsetof(XvtSnapshotCraftData, warheadLauncherCount),
	  sizeof(((XvtSnapshotCraftData*)0)->warheadLauncherCount) },
	{ offsetof(CraftData, warheadSlotTypeIds), offsetof(XvtSnapshotCraftData, warheadSlotTypeIds),
	  sizeof(((XvtSnapshotCraftData*)0)->warheadSlotTypeIds) },
	{ offsetof(CraftData, warheadLauncherFlags), offsetof(XvtSnapshotCraftData, warheadLauncherFlags),
	  sizeof(((XvtSnapshotCraftData*)0)->warheadLauncherFlags) },
	{ offsetof(CraftData, warheadLauncherCooldownTicks),
	  offsetof(XvtSnapshotCraftData, warheadLauncherCooldownTicks),
	  sizeof(((XvtSnapshotCraftData*)0)->warheadLauncherCooldownTicks) },
	{ offsetof(CraftData, warheadLockTicks), offsetof(XvtSnapshotCraftData, warheadLockTicks),
	  sizeof(((XvtSnapshotCraftData*)0)->warheadLockTicks) },
	{ offsetof(CraftData, beamTypeId), offsetof(XvtSnapshotCraftData, beamTypeId),
	  sizeof(((XvtSnapshotCraftData*)0)->beamTypeId) },
	{ offsetof(CraftData, beamRechargeLevel), offsetof(XvtSnapshotCraftData, beamRechargeLevel),
	  sizeof(((XvtSnapshotCraftData*)0)->beamRechargeLevel) },
	{ offsetof(CraftData, beamCharge), offsetof(XvtSnapshotCraftData, beamCharge),
	  sizeof(((XvtSnapshotCraftData*)0)->beamCharge) },
	{ offsetof(CraftData, beamActive), offsetof(XvtSnapshotCraftData, beamActive),
	  sizeof(((XvtSnapshotCraftData*)0)->beamActive) },
	{ offsetof(CraftData, beamOutput), offsetof(XvtSnapshotCraftData, beamOutput),
	  sizeof(((XvtSnapshotCraftData*)0)->beamOutput) },
	{ offsetof(CraftData, beamTargetObjIdx), offsetof(XvtSnapshotCraftData, beamTargetObjIdx),
	  sizeof(((XvtSnapshotCraftData*)0)->beamTargetObjIdx) },
	{ offsetof(CraftData, cmTypeId), offsetof(XvtSnapshotCraftData, cmTypeId),
	  sizeof(((XvtSnapshotCraftData*)0)->cmTypeId) },
	{ offsetof(CraftData, cmAmmoCount), offsetof(XvtSnapshotCraftData, cmAmmoCount),
	  sizeof(((XvtSnapshotCraftData*)0)->cmAmmoCount) },
	{ offsetof(CraftData, chaffActiveSeconds), offsetof(XvtSnapshotCraftData, chaffActiveSeconds),
	  sizeof(((XvtSnapshotCraftData*)0)->chaffActiveSeconds) },
	{ offsetof(CraftData, cmFireCooldownTimer), offsetof(XvtSnapshotCraftData, cmFireCooldownTimer),
	  sizeof(((XvtSnapshotCraftData*)0)->cmFireCooldownTimer) },
	{ offsetof(CraftData, weaponStats), offsetof(XvtSnapshotCraftData, weaponStats),
	  sizeof(((XvtSnapshotCraftData*)0)->weaponStats) },
	{ offsetof(CraftData, field_256), offsetof(XvtSnapshotCraftData, field_256),
	  sizeof(((XvtSnapshotCraftData*)0)->field_256) },
	{ offsetof(CraftData, field_29F), offsetof(XvtSnapshotCraftData, field_29F),
	  sizeof(((XvtSnapshotCraftData*)0)->field_29F) },
	{ offsetof(CraftData, systemDisplaySlotBySystem),
	  offsetof(XvtSnapshotCraftData, systemDisplaySlotBySystem),
	  sizeof(((XvtSnapshotCraftData*)0)->systemDisplaySlotBySystem) },
	{ offsetof(CraftData, systemHealth), offsetof(XvtSnapshotCraftData, systemHealth),
	  sizeof(((XvtSnapshotCraftData*)0)->systemHealth) },
	{ offsetof(CraftData, systemRepairSeconds), offsetof(XvtSnapshotCraftData, systemRepairSeconds),
	  sizeof(((XvtSnapshotCraftData*)0)->systemRepairSeconds) },
	{ offsetof(CraftData, componentState), offsetof(XvtSnapshotCraftData, componentState),
	  sizeof(((XvtSnapshotCraftData*)0)->componentState) },
	{ offsetof(CraftData, meshRotation), offsetof(XvtSnapshotCraftData, meshRotation),
	  sizeof(((XvtSnapshotCraftData*)0)->meshRotation) },
	{ offsetof(CraftData, componentHp), offsetof(XvtSnapshotCraftData, componentHp),
	  sizeof(((XvtSnapshotCraftData*)0)->componentHp) },
	{ offsetof(CraftData, playerCommandAvoidTargetObjIdx),
	  offsetof(XvtSnapshotCraftData, playerCommandAvoidTargetObjIdx),
	  sizeof(((XvtSnapshotCraftData*)0)->playerCommandAvoidTargetObjIdx) },
	{ offsetof(CraftData, weaponSlots), offsetof(XvtSnapshotCraftData, weaponSlots),
	  sizeof(((XvtSnapshotCraftData*)0)->weaponSlots) },
	{ offsetof(CraftData, effectiveAiObjectSignature),
	  offsetof(XvtSnapshotCraftData, effectiveAiObjectSignature),
	  sizeof(((XvtSnapshotCraftData*)0)->effectiveAiObjectSignature) },
	{ offsetof(CraftData, turretTargetStates), offsetof(XvtSnapshotCraftData, turretTargetStates),
	  sizeof(((XvtSnapshotCraftData*)0)->turretTargetStates) },
	{ offsetof(CraftData, field_3F2), offsetof(XvtSnapshotCraftData, field_3F2),
	  sizeof(((XvtSnapshotCraftData*)0)->field_3F2) },
};

void XvtSnapshot_EncodeCraftData(XvtSnapshotCraftData* record, const CraftData* live) {
	XvtSnapshot_CopyFields((void*)record, (void*)live, g_CraftDataFields,
						   sizeof(g_CraftDataFields) / sizeof(g_CraftDataFields[0]), 0);
	for (size_t i = 0; i < sizeof(record->turretObjectLinks) / sizeof(record->turretObjectLinks[0]); ++i) {
		record->turretObjectLinks[i] =
			live->turretObjectLinks[i]
				? (uint32_t)((live->turretObjectLinks[i] - g_objectTable) * sizeof(XvtSnapshotObjectRecord) +
							 1)
				: 0;
	}
	record->effectiveAiObjectLink =
		live->effectiveAiObjectLink
			? (uint32_t)((live->effectiveAiObjectLink - g_objectTable) * sizeof(XvtSnapshotObjectRecord) + 1)
			: 0;
}

void XvtSnapshot_DecodeCraftData(CraftData* live, const XvtSnapshotCraftData* record) {
	XvtSnapshot_CopyFields((void*)record, (void*)live, g_CraftDataFields,
						   sizeof(g_CraftDataFields) / sizeof(g_CraftDataFields[0]), 1);
	for (size_t i = 0; i < sizeof(record->turretObjectLinks) / sizeof(record->turretObjectLinks[0]); ++i) {
		live->turretObjectLinks[i] =
			record->turretObjectLinks[i]
				? &g_objectTable[(record->turretObjectLinks[i] - 1) / sizeof(XvtSnapshotObjectRecord)]
				: NULL;
	}
	live->effectiveAiObjectLink =
		record->effectiveAiObjectLink
			? &g_objectTable[(record->effectiveAiObjectLink - 1) / sizeof(XvtSnapshotObjectRecord)]
			: NULL;
}

static const XvtSnapshotField g_MobileObjectCharDataFields[] = {
	{ offsetof(MobileObjectCharData, skillValue), offsetof(XvtSnapshotMobileObjectCharData, skillValue),
	  sizeof(((XvtSnapshotMobileObjectCharData*)0)->skillValue) },
	{ offsetof(MobileObjectCharData, reserved02), offsetof(XvtSnapshotMobileObjectCharData, reserved02),
	  sizeof(((XvtSnapshotMobileObjectCharData*)0)->reserved02) },
	{ offsetof(MobileObjectCharData, aiController.currentOrderSlot),
	  offsetof(XvtSnapshotMobileObjectCharData, aiController.currentOrderSlot),
	  sizeof(((XvtSnapshotMobileObjectCharData*)0)->aiController.currentOrderSlot) },
	{ offsetof(MobileObjectCharData, aiController.orderProgress),
	  offsetof(XvtSnapshotMobileObjectCharData, aiController.orderProgress),
	  sizeof(((XvtSnapshotMobileObjectCharData*)0)->aiController.orderProgress) },
	{ offsetof(MobileObjectCharData, aiController.skippedToOrder4),
	  offsetof(XvtSnapshotMobileObjectCharData, aiController.skippedToOrder4),
	  sizeof(((XvtSnapshotMobileObjectCharData*)0)->aiController.skippedToOrder4) },
	{ offsetof(MobileObjectCharData, aiController.pendingPlanId),
	  offsetof(XvtSnapshotMobileObjectCharData, aiController.pendingPlanId),
	  sizeof(((XvtSnapshotMobileObjectCharData*)0)->aiController.pendingPlanId) },
	{ offsetof(MobileObjectCharData, aiController.currentPlanId),
	  offsetof(XvtSnapshotMobileObjectCharData, aiController.currentPlanId),
	  sizeof(((XvtSnapshotMobileObjectCharData*)0)->aiController.currentPlanId) },
	{ offsetof(MobileObjectCharData, aiController.waypointIndex),
	  offsetof(XvtSnapshotMobileObjectCharData, aiController.waypointIndex),
	  sizeof(((XvtSnapshotMobileObjectCharData*)0)->aiController.waypointIndex) },
	{ offsetof(MobileObjectCharData, aiController.savedPlanId),
	  offsetof(XvtSnapshotMobileObjectCharData, aiController.savedPlanId),
	  sizeof(((XvtSnapshotMobileObjectCharData*)0)->aiController.savedPlanId) },
	{ offsetof(MobileObjectCharData, aiController.thinkInterval),
	  offsetof(XvtSnapshotMobileObjectCharData, aiController.thinkInterval),
	  sizeof(((XvtSnapshotMobileObjectCharData*)0)->aiController.thinkInterval) },
	{ offsetof(MobileObjectCharData, aiController.thinkTimer),
	  offsetof(XvtSnapshotMobileObjectCharData, aiController.thinkTimer),
	  sizeof(((XvtSnapshotMobileObjectCharData*)0)->aiController.thinkTimer) },
	{ offsetof(MobileObjectCharData, aiController.savedRandSeed),
	  offsetof(XvtSnapshotMobileObjectCharData, aiController.savedRandSeed),
	  sizeof(((XvtSnapshotMobileObjectCharData*)0)->aiController.savedRandSeed) },
	{ offsetof(MobileObjectCharData, aiController.targetObjIdx),
	  offsetof(XvtSnapshotMobileObjectCharData, aiController.targetObjIdx),
	  sizeof(((XvtSnapshotMobileObjectCharData*)0)->aiController.targetObjIdx) },
	{ offsetof(MobileObjectCharData, aiController.targetSignature),
	  offsetof(XvtSnapshotMobileObjectCharData, aiController.targetSignature),
	  sizeof(((XvtSnapshotMobileObjectCharData*)0)->aiController.targetSignature) },
	{ offsetof(MobileObjectCharData, aiController.targetComponent),
	  offsetof(XvtSnapshotMobileObjectCharData, aiController.targetComponent),
	  sizeof(((XvtSnapshotMobileObjectCharData*)0)->aiController.targetComponent) },
	{ offsetof(MobileObjectCharData, aiController.hasLiveTarget),
	  offsetof(XvtSnapshotMobileObjectCharData, aiController.hasLiveTarget),
	  sizeof(((XvtSnapshotMobileObjectCharData*)0)->aiController.hasLiveTarget) },
	{ offsetof(MobileObjectCharData, aiController.aimPointX),
	  offsetof(XvtSnapshotMobileObjectCharData, aiController.aimPointX),
	  sizeof(((XvtSnapshotMobileObjectCharData*)0)->aiController.aimPointX) },
	{ offsetof(MobileObjectCharData, aiController.aimPointY),
	  offsetof(XvtSnapshotMobileObjectCharData, aiController.aimPointY),
	  sizeof(((XvtSnapshotMobileObjectCharData*)0)->aiController.aimPointY) },
	{ offsetof(MobileObjectCharData, aiController.aimPointZ),
	  offsetof(XvtSnapshotMobileObjectCharData, aiController.aimPointZ),
	  sizeof(((XvtSnapshotMobileObjectCharData*)0)->aiController.aimPointZ) },
	{ offsetof(MobileObjectCharData, aiController.candidateTargetIdx),
	  offsetof(XvtSnapshotMobileObjectCharData, aiController.candidateTargetIdx),
	  sizeof(((XvtSnapshotMobileObjectCharData*)0)->aiController.candidateTargetIdx) },
	{ offsetof(MobileObjectCharData, aiController.escortTargetFG),
	  offsetof(XvtSnapshotMobileObjectCharData, aiController.escortTargetFG),
	  sizeof(((XvtSnapshotMobileObjectCharData*)0)->aiController.escortTargetFG) },
	{ offsetof(MobileObjectCharData, aiController.targetZAngle),
	  offsetof(XvtSnapshotMobileObjectCharData, aiController.targetZAngle),
	  sizeof(((XvtSnapshotMobileObjectCharData*)0)->aiController.targetZAngle) },
	{ offsetof(MobileObjectCharData, aiController.targetRoll),
	  offsetof(XvtSnapshotMobileObjectCharData, aiController.targetRoll),
	  sizeof(((XvtSnapshotMobileObjectCharData*)0)->aiController.targetRoll) },
	{ offsetof(MobileObjectCharData, aiController.targetXYAngle),
	  offsetof(XvtSnapshotMobileObjectCharData, aiController.targetXYAngle),
	  sizeof(((XvtSnapshotMobileObjectCharData*)0)->aiController.targetXYAngle) },
	{ offsetof(MobileObjectCharData, aiController.maneuverMode),
	  offsetof(XvtSnapshotMobileObjectCharData, aiController.maneuverMode),
	  sizeof(((XvtSnapshotMobileObjectCharData*)0)->aiController.maneuverMode) },
	{ offsetof(MobileObjectCharData, aiController.maneuverPhase),
	  offsetof(XvtSnapshotMobileObjectCharData, aiController.maneuverPhase),
	  sizeof(((XvtSnapshotMobileObjectCharData*)0)->aiController.maneuverPhase) },
	{ offsetof(MobileObjectCharData, aiController.maneuverTimer),
	  offsetof(XvtSnapshotMobileObjectCharData, aiController.maneuverTimer),
	  sizeof(((XvtSnapshotMobileObjectCharData*)0)->aiController.maneuverTimer) },
	{ offsetof(MobileObjectCharData, aiController.secondaryManeuverTimer),
	  offsetof(XvtSnapshotMobileObjectCharData, aiController.secondaryManeuverTimer),
	  sizeof(((XvtSnapshotMobileObjectCharData*)0)->aiController.secondaryManeuverTimer) },
	{ offsetof(MobileObjectCharData, reserved40), offsetof(XvtSnapshotMobileObjectCharData, reserved40),
	  sizeof(((XvtSnapshotMobileObjectCharData*)0)->reserved40) },
};

void XvtSnapshot_EncodeMobileObjectCharData(XvtSnapshotMobileObjectCharData* record,
											const MobileObjectCharData* live) {
	XvtSnapshot_CopyFields((void*)record, (void*)live, g_MobileObjectCharDataFields,
						   sizeof(g_MobileObjectCharDataFields) / sizeof(g_MobileObjectCharDataFields[0]), 0);
}

void XvtSnapshot_DecodeMobileObjectCharData(MobileObjectCharData* live,
											const XvtSnapshotMobileObjectCharData* record) {
	XvtSnapshot_CopyFields((void*)record, (void*)live, g_MobileObjectCharDataFields,
						   sizeof(g_MobileObjectCharDataFields) / sizeof(g_MobileObjectCharDataFields[0]), 1);
}

static const XvtSnapshotField g_PlayerDataFields[] = {
	{ offsetof(PlayerData, objectIndex), offsetof(XvtSnapshotPlayerData, objectIndex),
	  sizeof(((XvtSnapshotPlayerData*)0)->objectIndex) },
	{ offsetof(PlayerData, boundObjectSignature), offsetof(XvtSnapshotPlayerData, boundObjectSignature),
	  sizeof(((XvtSnapshotPlayerData*)0)->boundObjectSignature) },
	{ offsetof(PlayerData, pilotRating), offsetof(XvtSnapshotPlayerData, pilotRating),
	  sizeof(((XvtSnapshotPlayerData*)0)->pilotRating) },
	{ offsetof(PlayerData, iff), offsetof(XvtSnapshotPlayerData, iff),
	  sizeof(((XvtSnapshotPlayerData*)0)->iff) },
	{ offsetof(PlayerData, team), offsetof(XvtSnapshotPlayerData, team),
	  sizeof(((XvtSnapshotPlayerData*)0)->team) },
	{ offsetof(PlayerData, boundFlightGroupIdx), offsetof(XvtSnapshotPlayerData, boundFlightGroupIdx),
	  sizeof(((XvtSnapshotPlayerData*)0)->boundFlightGroupIdx) },
	{ offsetof(PlayerData, participationState), offsetof(XvtSnapshotPlayerData, participationState),
	  sizeof(((XvtSnapshotPlayerData*)0)->participationState) },
	{ offsetof(PlayerData, awaitingNewCraft), offsetof(XvtSnapshotPlayerData, awaitingNewCraft),
	  sizeof(((XvtSnapshotPlayerData*)0)->awaitingNewCraft) },
	{ offsetof(PlayerData, boundCraftEngineGlowCount),
	  offsetof(XvtSnapshotPlayerData, boundCraftEngineGlowCount),
	  sizeof(((XvtSnapshotPlayerData*)0)->boundCraftEngineGlowCount) },
	{ offsetof(PlayerData, mapCameraState), offsetof(XvtSnapshotPlayerData, mapCameraState),
	  sizeof(((XvtSnapshotPlayerData*)0)->mapCameraState) },
	{ offsetof(PlayerData, hyperspacePhase), offsetof(XvtSnapshotPlayerData, hyperspacePhase),
	  sizeof(((XvtSnapshotPlayerData*)0)->hyperspacePhase) },
	{ offsetof(PlayerData, hyperspaceRuntime), offsetof(XvtSnapshotPlayerData, hyperspaceRuntime),
	  sizeof(((XvtSnapshotPlayerData*)0)->hyperspaceRuntime) },
	{ offsetof(PlayerData, targetBoxEnabled), offsetof(XvtSnapshotPlayerData, targetBoxEnabled),
	  sizeof(((XvtSnapshotPlayerData*)0)->targetBoxEnabled) },
	{ offsetof(PlayerData, currentTargetObjectIdx), offsetof(XvtSnapshotPlayerData, currentTargetObjectIdx),
	  sizeof(((XvtSnapshotPlayerData*)0)->currentTargetObjectIdx) },
	{ offsetof(PlayerData, targetCycleStart), offsetof(XvtSnapshotPlayerData, targetCycleStart),
	  sizeof(((XvtSnapshotPlayerData*)0)->targetCycleStart) },
	{ offsetof(PlayerData, targetPresetSlot), offsetof(XvtSnapshotPlayerData, targetPresetSlot),
	  sizeof(((XvtSnapshotPlayerData*)0)->targetPresetSlot) },
	{ offsetof(PlayerData, missileLockState), offsetof(XvtSnapshotPlayerData, missileLockState),
	  sizeof(((XvtSnapshotPlayerData*)0)->missileLockState) },
	{ offsetof(PlayerData, selectedWeaponBank), offsetof(XvtSnapshotPlayerData, selectedWeaponBank),
	  sizeof(((XvtSnapshotPlayerData*)0)->selectedWeaponBank) },
	{ offsetof(PlayerData, selectedWeaponMode), offsetof(XvtSnapshotPlayerData, selectedWeaponMode),
	  sizeof(((XvtSnapshotPlayerData*)0)->selectedWeaponMode) },
	{ offsetof(PlayerData, selectedTargetComponent), offsetof(XvtSnapshotPlayerData, selectedTargetComponent),
	  sizeof(((XvtSnapshotPlayerData*)0)->selectedTargetComponent) },
	{ offsetof(PlayerData, targetingState), offsetof(XvtSnapshotPlayerData, targetingState),
	  sizeof(((XvtSnapshotPlayerData*)0)->targetingState) },
	{ offsetof(PlayerData, engineWashSourceObjIdx), offsetof(XvtSnapshotPlayerData, engineWashSourceObjIdx),
	  sizeof(((XvtSnapshotPlayerData*)0)->engineWashSourceObjIdx) },
	{ offsetof(PlayerData, engineWashStrength), offsetof(XvtSnapshotPlayerData, engineWashStrength),
	  sizeof(((XvtSnapshotPlayerData*)0)->engineWashStrength) },
	{ offsetof(PlayerData, throttlePreset), offsetof(XvtSnapshotPlayerData, throttlePreset),
	  sizeof(((XvtSnapshotPlayerData*)0)->throttlePreset) },
	{ offsetof(PlayerData, laserPreset), offsetof(XvtSnapshotPlayerData, laserPreset),
	  sizeof(((XvtSnapshotPlayerData*)0)->laserPreset) },
	{ offsetof(PlayerData, shieldPreset), offsetof(XvtSnapshotPlayerData, shieldPreset),
	  sizeof(((XvtSnapshotPlayerData*)0)->shieldPreset) },
	{ offsetof(PlayerData, beamPreset), offsetof(XvtSnapshotPlayerData, beamPreset),
	  sizeof(((XvtSnapshotPlayerData*)0)->beamPreset) },
	{ offsetof(PlayerData, savedCraftSettings), offsetof(XvtSnapshotPlayerData, savedCraftSettings),
	  sizeof(((XvtSnapshotPlayerData*)0)->savedCraftSettings) },
	{ offsetof(PlayerData, savedHudViewState), offsetof(XvtSnapshotPlayerData, savedHudViewState),
	  sizeof(((XvtSnapshotPlayerData*)0)->savedHudViewState) },
	{ offsetof(PlayerData, pendingActionId), offsetof(XvtSnapshotPlayerData, pendingActionId),
	  sizeof(((XvtSnapshotPlayerData*)0)->pendingActionId) },
	{ offsetof(PlayerData, pendingActionParam), offsetof(XvtSnapshotPlayerData, pendingActionParam),
	  sizeof(((XvtSnapshotPlayerData*)0)->pendingActionParam) },
	{ offsetof(PlayerData, pendingActionIssuerPlayerIdx),
	  offsetof(XvtSnapshotPlayerData, pendingActionIssuerPlayerIdx),
	  sizeof(((XvtSnapshotPlayerData*)0)->pendingActionIssuerPlayerIdx) },
	{ offsetof(PlayerData, yawRollSwap), offsetof(XvtSnapshotPlayerData, yawRollSwap),
	  sizeof(((XvtSnapshotPlayerData*)0)->yawRollSwap) },
	{ offsetof(PlayerData, smoothedInputYaw), offsetof(XvtSnapshotPlayerData, smoothedInputYaw),
	  sizeof(((XvtSnapshotPlayerData*)0)->smoothedInputYaw) },
	{ offsetof(PlayerData, smoothedInputPitch), offsetof(XvtSnapshotPlayerData, smoothedInputPitch),
	  sizeof(((XvtSnapshotPlayerData*)0)->smoothedInputPitch) },
	{ offsetof(PlayerData, savedKeyMods), offsetof(XvtSnapshotPlayerData, savedKeyMods),
	  sizeof(((XvtSnapshotPlayerData*)0)->savedKeyMods) },
	{ offsetof(PlayerData, keyModsHoldTimer), offsetof(XvtSnapshotPlayerData, keyModsHoldTimer),
	  sizeof(((XvtSnapshotPlayerData*)0)->keyModsHoldTimer) },
	{ offsetof(PlayerData, hardpointWorldX), offsetof(XvtSnapshotPlayerData, hardpointWorldX),
	  sizeof(((XvtSnapshotPlayerData*)0)->hardpointWorldX) },
	{ offsetof(PlayerData, hardpointWorldY), offsetof(XvtSnapshotPlayerData, hardpointWorldY),
	  sizeof(((XvtSnapshotPlayerData*)0)->hardpointWorldY) },
	{ offsetof(PlayerData, hardpointWorldZ), offsetof(XvtSnapshotPlayerData, hardpointWorldZ),
	  sizeof(((XvtSnapshotPlayerData*)0)->hardpointWorldZ) },
	{ offsetof(PlayerData, prevHardpointWorldX), offsetof(XvtSnapshotPlayerData, prevHardpointWorldX),
	  sizeof(((XvtSnapshotPlayerData*)0)->prevHardpointWorldX) },
	{ offsetof(PlayerData, prevHardpointWorldY), offsetof(XvtSnapshotPlayerData, prevHardpointWorldY),
	  sizeof(((XvtSnapshotPlayerData*)0)->prevHardpointWorldY) },
	{ offsetof(PlayerData, prevHardpointWorldZ), offsetof(XvtSnapshotPlayerData, prevHardpointWorldZ),
	  sizeof(((XvtSnapshotPlayerData*)0)->prevHardpointWorldZ) },
	{ offsetof(PlayerData, missionStats), offsetof(XvtSnapshotPlayerData, missionStats),
	  sizeof(((XvtSnapshotPlayerData*)0)->missionStats) },
	{ offsetof(PlayerData, warheadsFired), offsetof(XvtSnapshotPlayerData, warheadsFired),
	  sizeof(((XvtSnapshotPlayerData*)0)->warheadsFired) },
	{ offsetof(PlayerData, perMissionKills), offsetof(XvtSnapshotPlayerData, perMissionKills),
	  sizeof(((XvtSnapshotPlayerData*)0)->perMissionKills) },
	{ offsetof(PlayerData, msgText), offsetof(XvtSnapshotPlayerData, msgText),
	  sizeof(((XvtSnapshotPlayerData*)0)->msgText) },
	{ offsetof(PlayerData, msgLength), offsetof(XvtSnapshotPlayerData, msgLength),
	  sizeof(((XvtSnapshotPlayerData*)0)->msgLength) },
	{ offsetof(PlayerData, chatRecipientMode), offsetof(XvtSnapshotPlayerData, chatRecipientMode),
	  sizeof(((XvtSnapshotPlayerData*)0)->chatRecipientMode) },
	{ offsetof(PlayerData, viewState.cameraWorldX), offsetof(XvtSnapshotPlayerData, viewState.cameraWorldX),
	  sizeof(((XvtSnapshotPlayerData*)0)->viewState.cameraWorldX) },
	{ offsetof(PlayerData, viewState.cameraWorldY), offsetof(XvtSnapshotPlayerData, viewState.cameraWorldY),
	  sizeof(((XvtSnapshotPlayerData*)0)->viewState.cameraWorldY) },
	{ offsetof(PlayerData, viewState.cameraWorldZ), offsetof(XvtSnapshotPlayerData, viewState.cameraWorldZ),
	  sizeof(((XvtSnapshotPlayerData*)0)->viewState.cameraWorldZ) },
	{ offsetof(PlayerData, viewState.cameraFocusObjIdx),
	  offsetof(XvtSnapshotPlayerData, viewState.cameraFocusObjIdx),
	  sizeof(((XvtSnapshotPlayerData*)0)->viewState.cameraFocusObjIdx) },
	{ offsetof(PlayerData, viewState.aimTargetIdx), offsetof(XvtSnapshotPlayerData, viewState.aimTargetIdx),
	  sizeof(((XvtSnapshotPlayerData*)0)->viewState.aimTargetIdx) },
	{ offsetof(PlayerData, viewState.viewPitch), offsetof(XvtSnapshotPlayerData, viewState.viewPitch),
	  sizeof(((XvtSnapshotPlayerData*)0)->viewState.viewPitch) },
	{ offsetof(PlayerData, viewState.viewYaw), offsetof(XvtSnapshotPlayerData, viewState.viewYaw),
	  sizeof(((XvtSnapshotPlayerData*)0)->viewState.viewYaw) },
	{ offsetof(PlayerData, viewState.viewRoll), offsetof(XvtSnapshotPlayerData, viewState.viewRoll),
	  sizeof(((XvtSnapshotPlayerData*)0)->viewState.viewRoll) },
	{ offsetof(PlayerData, viewState.viewAngleD), offsetof(XvtSnapshotPlayerData, viewState.viewAngleD),
	  sizeof(((XvtSnapshotPlayerData*)0)->viewState.viewAngleD) },
	{ offsetof(PlayerData, viewState.hudAimX), offsetof(XvtSnapshotPlayerData, viewState.hudAimX),
	  sizeof(((XvtSnapshotPlayerData*)0)->viewState.hudAimX) },
	{ offsetof(PlayerData, viewState.hudAimY), offsetof(XvtSnapshotPlayerData, viewState.hudAimY),
	  sizeof(((XvtSnapshotPlayerData*)0)->viewState.hudAimY) },
	{ offsetof(PlayerData, viewState.hudStateLive), offsetof(XvtSnapshotPlayerData, viewState.hudStateLive),
	  sizeof(((XvtSnapshotPlayerData*)0)->viewState.hudStateLive) },
	{ offsetof(PlayerData, viewState.hudStateMirror),
	  offsetof(XvtSnapshotPlayerData, viewState.hudStateMirror),
	  sizeof(((XvtSnapshotPlayerData*)0)->viewState.hudStateMirror) },
	{ offsetof(PlayerData, viewState.hudAimXSnapState),
	  offsetof(XvtSnapshotPlayerData, viewState.hudAimXSnapState),
	  sizeof(((XvtSnapshotPlayerData*)0)->viewState.hudAimXSnapState) },
	{ offsetof(PlayerData, viewState.savedHudStateByte),
	  offsetof(XvtSnapshotPlayerData, viewState.savedHudStateByte),
	  sizeof(((XvtSnapshotPlayerData*)0)->viewState.savedHudStateByte) },
	{ offsetof(PlayerData, viewState.field_20), offsetof(XvtSnapshotPlayerData, viewState.field_20),
	  sizeof(((XvtSnapshotPlayerData*)0)->viewState.field_20) },
	{ offsetof(PlayerData, viewState.savedHudAimX), offsetof(XvtSnapshotPlayerData, viewState.savedHudAimX),
	  sizeof(((XvtSnapshotPlayerData*)0)->viewState.savedHudAimX) },
	{ offsetof(PlayerData, viewState.savedHudAimY), offsetof(XvtSnapshotPlayerData, viewState.savedHudAimY),
	  sizeof(((XvtSnapshotPlayerData*)0)->viewState.savedHudAimY) },
	{ offsetof(PlayerData, viewState.playerInputBlocked),
	  offsetof(XvtSnapshotPlayerData, viewState.playerInputBlocked),
	  sizeof(((XvtSnapshotPlayerData*)0)->viewState.playerInputBlocked) },
	{ offsetof(PlayerData, viewState.cameraDistanceStep),
	  offsetof(XvtSnapshotPlayerData, viewState.cameraDistanceStep),
	  sizeof(((XvtSnapshotPlayerData*)0)->viewState.cameraDistanceStep) },
	{ offsetof(PlayerData, viewState.externalCameraActive),
	  offsetof(XvtSnapshotPlayerData, viewState.externalCameraActive),
	  sizeof(((XvtSnapshotPlayerData*)0)->viewState.externalCameraActive) },
	{ offsetof(PlayerData, viewState.cameraDistance),
	  offsetof(XvtSnapshotPlayerData, viewState.cameraDistance),
	  sizeof(((XvtSnapshotPlayerData*)0)->viewState.cameraDistance) },
	{ offsetof(PlayerData, viewState.transitionTimer),
	  offsetof(XvtSnapshotPlayerData, viewState.transitionTimer),
	  sizeof(((XvtSnapshotPlayerData*)0)->viewState.transitionTimer) },
	{ offsetof(PlayerData, viewState.cameraRollHistory),
	  offsetof(XvtSnapshotPlayerData, viewState.cameraRollHistory),
	  sizeof(((XvtSnapshotPlayerData*)0)->viewState.cameraRollHistory) },
	{ offsetof(PlayerData, viewState.cameraPitchHistory),
	  offsetof(XvtSnapshotPlayerData, viewState.cameraPitchHistory),
	  sizeof(((XvtSnapshotPlayerData*)0)->viewState.cameraPitchHistory) },
	{ offsetof(PlayerData, viewState.cameraYawHistory),
	  offsetof(XvtSnapshotPlayerData, viewState.cameraYawHistory),
	  sizeof(((XvtSnapshotPlayerData*)0)->viewState.cameraYawHistory) },
	{ offsetof(PlayerData, viewState.field_199), offsetof(XvtSnapshotPlayerData, viewState.field_199),
	  sizeof(((XvtSnapshotPlayerData*)0)->viewState.field_199) },
	{ offsetof(PlayerData, network.flightResolutionMode),
	  offsetof(XvtSnapshotPlayerData, network.flightResolutionMode),
	  sizeof(((XvtSnapshotPlayerData*)0)->network.flightResolutionMode) },
	{ offsetof(PlayerData, network.directPlayId), offsetof(XvtSnapshotPlayerData, network.directPlayId),
	  sizeof(((XvtSnapshotPlayerData*)0)->network.directPlayId) },
	{ offsetof(PlayerData, lockstepTimestamp), offsetof(XvtSnapshotPlayerData, lockstepTimestamp),
	  sizeof(((XvtSnapshotPlayerData*)0)->lockstepTimestamp) },
	{ offsetof(PlayerData, savedX), offsetof(XvtSnapshotPlayerData, savedX),
	  sizeof(((XvtSnapshotPlayerData*)0)->savedX) },
	{ offsetof(PlayerData, savedY), offsetof(XvtSnapshotPlayerData, savedY),
	  sizeof(((XvtSnapshotPlayerData*)0)->savedY) },
	{ offsetof(PlayerData, savedZ), offsetof(XvtSnapshotPlayerData, savedZ),
	  sizeof(((XvtSnapshotPlayerData*)0)->savedZ) },
	{ offsetof(PlayerData, savedRoll), offsetof(XvtSnapshotPlayerData, savedRoll),
	  sizeof(((XvtSnapshotPlayerData*)0)->savedRoll) },
	{ offsetof(PlayerData, savedPitch), offsetof(XvtSnapshotPlayerData, savedPitch),
	  sizeof(((XvtSnapshotPlayerData*)0)->savedPitch) },
	{ offsetof(PlayerData, savedYaw), offsetof(XvtSnapshotPlayerData, savedYaw),
	  sizeof(((XvtSnapshotPlayerData*)0)->savedYaw) },
	{ offsetof(PlayerData, savedLifetimeTimer), offsetof(XvtSnapshotPlayerData, savedLifetimeTimer),
	  sizeof(((XvtSnapshotPlayerData*)0)->savedLifetimeTimer) },
	{ offsetof(PlayerData, savedSpeed), offsetof(XvtSnapshotPlayerData, savedSpeed),
	  sizeof(((XvtSnapshotPlayerData*)0)->savedSpeed) },
	{ offsetof(PlayerData, savedSpeedRemainder), offsetof(XvtSnapshotPlayerData, savedSpeedRemainder),
	  sizeof(((XvtSnapshotPlayerData*)0)->savedSpeedRemainder) },
	{ offsetof(PlayerData, savedRollImpulseRate), offsetof(XvtSnapshotPlayerData, savedRollImpulseRate),
	  sizeof(((XvtSnapshotPlayerData*)0)->savedRollImpulseRate) },
	{ offsetof(PlayerData, savedObjectSignature), offsetof(XvtSnapshotPlayerData, savedObjectSignature),
	  sizeof(((XvtSnapshotPlayerData*)0)->savedObjectSignature) },
	{ offsetof(PlayerData, savedAwaitingNewCraft), offsetof(XvtSnapshotPlayerData, savedAwaitingNewCraft),
	  sizeof(((XvtSnapshotPlayerData*)0)->savedAwaitingNewCraft) },
	{ offsetof(PlayerData, pendingActionTimer), offsetof(XvtSnapshotPlayerData, pendingActionTimer),
	  sizeof(((XvtSnapshotPlayerData*)0)->pendingActionTimer) },
	{ offsetof(PlayerData, beamFireCooldownTimer), offsetof(XvtSnapshotPlayerData, beamFireCooldownTimer),
	  sizeof(((XvtSnapshotPlayerData*)0)->beamFireCooldownTimer) },
	{ offsetof(PlayerData, field_5B5), offsetof(XvtSnapshotPlayerData, field_5B5),
	  sizeof(((XvtSnapshotPlayerData*)0)->field_5B5) },
	{ offsetof(PlayerData, nextEngineWashCheckTime), offsetof(XvtSnapshotPlayerData, nextEngineWashCheckTime),
	  sizeof(((XvtSnapshotPlayerData*)0)->nextEngineWashCheckTime) },
};

void XvtSnapshot_EncodePlayerData(XvtSnapshotPlayerData* record, const PlayerData* live) {
	XvtSnapshot_CopyFields((void*)record, (void*)live, g_PlayerDataFields,
						   sizeof(g_PlayerDataFields) / sizeof(g_PlayerDataFields[0]), 0);
}

void XvtSnapshot_DecodePlayerData(PlayerData* live, const XvtSnapshotPlayerData* record) {
	XvtSnapshot_CopyFields((void*)record, (void*)live, g_PlayerDataFields,
						   sizeof(g_PlayerDataFields) / sizeof(g_PlayerDataFields[0]), 1);
}

static const XvtSnapshotField g_FlightMissionStateFields[] = {
	{ offsetof(FlightMissionState, missionEndPending),
	  offsetof(XvtSnapshotFlightMissionState, missionEndPending),
	  sizeof(((XvtSnapshotFlightMissionState*)0)->missionEndPending) },
	{ offsetof(FlightMissionState, provingGroundsModeActive),
	  offsetof(XvtSnapshotFlightMissionState, provingGroundsModeActive),
	  sizeof(((XvtSnapshotFlightMissionState*)0)->provingGroundsModeActive) },
	{ offsetof(FlightMissionState, provingGroundsCraftType),
	  offsetof(XvtSnapshotFlightMissionState, provingGroundsCraftType),
	  sizeof(((XvtSnapshotFlightMissionState*)0)->provingGroundsCraftType) },
	{ offsetof(FlightMissionState, provingGroundsLevel),
	  offsetof(XvtSnapshotFlightMissionState, provingGroundsLevel),
	  sizeof(((XvtSnapshotFlightMissionState*)0)->provingGroundsLevel) },
	{ offsetof(FlightMissionState, provingGroundsScore),
	  offsetof(XvtSnapshotFlightMissionState, provingGroundsScore),
	  sizeof(((XvtSnapshotFlightMissionState*)0)->provingGroundsScore) },
	{ offsetof(FlightMissionState, reserved08), offsetof(XvtSnapshotFlightMissionState, reserved08),
	  sizeof(((XvtSnapshotFlightMissionState*)0)->reserved08) },
	{ offsetof(FlightMissionState, provingGroundsCheckpointsPassed),
	  offsetof(XvtSnapshotFlightMissionState, provingGroundsCheckpointsPassed),
	  sizeof(((XvtSnapshotFlightMissionState*)0)->provingGroundsCheckpointsPassed) },
	{ offsetof(FlightMissionState, reserved0C), offsetof(XvtSnapshotFlightMissionState, reserved0C),
	  sizeof(((XvtSnapshotFlightMissionState*)0)->reserved0C) },
	{ offsetof(FlightMissionState, provingGroundsCheckpointsRemaining),
	  offsetof(XvtSnapshotFlightMissionState, provingGroundsCheckpointsRemaining),
	  sizeof(((XvtSnapshotFlightMissionState*)0)->provingGroundsCheckpointsRemaining) },
	{ offsetof(FlightMissionState, provingGroundsTargetsDestroyed),
	  offsetof(XvtSnapshotFlightMissionState, provingGroundsTargetsDestroyed),
	  sizeof(((XvtSnapshotFlightMissionState*)0)->provingGroundsTargetsDestroyed) },
	{ offsetof(FlightMissionState, provingGroundsTimeBonus),
	  offsetof(XvtSnapshotFlightMissionState, provingGroundsTimeBonus),
	  sizeof(((XvtSnapshotFlightMissionState*)0)->provingGroundsTimeBonus) },
	{ offsetof(FlightMissionState, difficulty), offsetof(XvtSnapshotFlightMissionState, difficulty),
	  sizeof(((XvtSnapshotFlightMissionState*)0)->difficulty) },
	{ offsetof(FlightMissionState, collisionsEnabled),
	  offsetof(XvtSnapshotFlightMissionState, collisionsEnabled),
	  sizeof(((XvtSnapshotFlightMissionState*)0)->collisionsEnabled) },
	{ offsetof(FlightMissionState, craftJumpingEnabled),
	  offsetof(XvtSnapshotFlightMissionState, craftJumpingEnabled),
	  sizeof(((XvtSnapshotFlightMissionState*)0)->craftJumpingEnabled) },
	{ offsetof(FlightMissionState, randomVariationEnabled),
	  offsetof(XvtSnapshotFlightMissionState, randomVariationEnabled),
	  sizeof(((XvtSnapshotFlightMissionState*)0)->randomVariationEnabled) },
	{ offsetof(FlightMissionState, battleLengthIndex),
	  offsetof(XvtSnapshotFlightMissionState, battleLengthIndex),
	  sizeof(((XvtSnapshotFlightMissionState*)0)->battleLengthIndex) },
	{ offsetof(FlightMissionState, locatePlayersEnabled),
	  offsetof(XvtSnapshotFlightMissionState, locatePlayersEnabled),
	  sizeof(((XvtSnapshotFlightMissionState*)0)->locatePlayersEnabled) },
	{ offsetof(FlightMissionState, aiOpponentsEnabled),
	  offsetof(XvtSnapshotFlightMissionState, aiOpponentsEnabled),
	  sizeof(((XvtSnapshotFlightMissionState*)0)->aiOpponentsEnabled) },
	{ offsetof(FlightMissionState, playerFlightGroupWaveMode),
	  offsetof(XvtSnapshotFlightMissionState, playerFlightGroupWaveMode),
	  sizeof(((XvtSnapshotFlightMissionState*)0)->playerFlightGroupWaveMode) },
	{ offsetof(FlightMissionState, missionTimeLimitMinutes),
	  offsetof(XvtSnapshotFlightMissionState, missionTimeLimitMinutes),
	  sizeof(((XvtSnapshotFlightMissionState*)0)->missionTimeLimitMinutes) },
	{ offsetof(FlightMissionState, teamVictoryTimeLimitMinutes),
	  offsetof(XvtSnapshotFlightMissionState, teamVictoryTimeLimitMinutes),
	  sizeof(((XvtSnapshotFlightMissionState*)0)->teamVictoryTimeLimitMinutes) },
	{ offsetof(FlightMissionState, teamVictoryTimeLimitStarted),
	  offsetof(XvtSnapshotFlightMissionState, teamVictoryTimeLimitStarted),
	  sizeof(((XvtSnapshotFlightMissionState*)0)->teamVictoryTimeLimitStarted) },
	{ offsetof(FlightMissionState, craftImpactBounceEnabled),
	  offsetof(XvtSnapshotFlightMissionState, craftImpactBounceEnabled),
	  sizeof(((XvtSnapshotFlightMissionState*)0)->craftImpactBounceEnabled) },
	{ offsetof(FlightMissionState, connectedPlayerCount),
	  offsetof(XvtSnapshotFlightMissionState, connectedPlayerCount),
	  sizeof(((XvtSnapshotFlightMissionState*)0)->connectedPlayerCount) },
	{ offsetof(FlightMissionState, maxConnectedPlayerCountThisMission),
	  offsetof(XvtSnapshotFlightMissionState, maxConnectedPlayerCountThisMission),
	  sizeof(((XvtSnapshotFlightMissionState*)0)->maxConnectedPlayerCountThisMission) },
	{ offsetof(FlightMissionState, runtime.teamScores),
	  offsetof(XvtSnapshotFlightMissionState, runtime.teamScores),
	  sizeof(((XvtSnapshotFlightMissionState*)0)->runtime.teamScores) },
	{ offsetof(FlightMissionState, runtime.teamKillStats),
	  offsetof(XvtSnapshotFlightMissionState, runtime.teamKillStats),
	  sizeof(((XvtSnapshotFlightMissionState*)0)->runtime.teamKillStats) },
	{ offsetof(FlightMissionState, runtime.teamFgInspectedCapturedCounts),
	  offsetof(XvtSnapshotFlightMissionState, runtime.teamFgInspectedCapturedCounts),
	  sizeof(((XvtSnapshotFlightMissionState*)0)->runtime.teamFgInspectedCapturedCounts) },
	{ offsetof(FlightMissionState, runtime.teamFgDesignationCode),
	  offsetof(XvtSnapshotFlightMissionState, runtime.teamFgDesignationCode),
	  sizeof(((XvtSnapshotFlightMissionState*)0)->runtime.teamFgDesignationCode) },
	{ offsetof(FlightMissionState, runtime.globalPrimaryGoalStatus),
	  offsetof(XvtSnapshotFlightMissionState, runtime.globalPrimaryGoalStatus),
	  sizeof(((XvtSnapshotFlightMissionState*)0)->runtime.globalPrimaryGoalStatus) },
	{ offsetof(FlightMissionState, runtime.globalGoalStatusUnused),
	  offsetof(XvtSnapshotFlightMissionState, runtime.globalGoalStatusUnused),
	  sizeof(((XvtSnapshotFlightMissionState*)0)->runtime.globalGoalStatusUnused) },
	{ offsetof(FlightMissionState, runtime.globalBonusGoalStatus),
	  offsetof(XvtSnapshotFlightMissionState, runtime.globalBonusGoalStatus),
	  sizeof(((XvtSnapshotFlightMissionState*)0)->runtime.globalBonusGoalStatus) },
	{ offsetof(FlightMissionState, runtime.teamGlobalGoalState),
	  offsetof(XvtSnapshotFlightMissionState, runtime.teamGlobalGoalState),
	  sizeof(((XvtSnapshotFlightMissionState*)0)->runtime.teamGlobalGoalState) },
	{ offsetof(FlightMissionState, runtime.teamGoalStatus),
	  offsetof(XvtSnapshotFlightMissionState, runtime.teamGoalStatus),
	  sizeof(((XvtSnapshotFlightMissionState*)0)->runtime.teamGoalStatus) },
	{ offsetof(FlightMissionState, runtime.globalGoalTriggerCounts),
	  offsetof(XvtSnapshotFlightMissionState, runtime.globalGoalTriggerCounts),
	  sizeof(((XvtSnapshotFlightMissionState*)0)->runtime.globalGoalTriggerCounts) },
	{ offsetof(FlightMissionState, runtime.teamMissionCompletionTimeSeconds),
	  offsetof(XvtSnapshotFlightMissionState, runtime.teamMissionCompletionTimeSeconds),
	  sizeof(((XvtSnapshotFlightMissionState*)0)->runtime.teamMissionCompletionTimeSeconds) },
	{ offsetof(FlightMissionState, runtime.teamHasCountableCraft),
	  offsetof(XvtSnapshotFlightMissionState, runtime.teamHasCountableCraft),
	  sizeof(((XvtSnapshotFlightMissionState*)0)->runtime.teamHasCountableCraft) },
	{ offsetof(FlightMissionState, runtime.teamReinforcementsCalled),
	  offsetof(XvtSnapshotFlightMissionState, runtime.teamReinforcementsCalled),
	  sizeof(((XvtSnapshotFlightMissionState*)0)->runtime.teamReinforcementsCalled) },
	{ offsetof(FlightMissionState, messageTriggered),
	  offsetof(XvtSnapshotFlightMissionState, messageTriggered),
	  sizeof(((XvtSnapshotFlightMissionState*)0)->messageTriggered) },
	{ offsetof(FlightMissionState, messageDelayCountdown),
	  offsetof(XvtSnapshotFlightMissionState, messageDelayCountdown),
	  sizeof(((XvtSnapshotFlightMissionState*)0)->messageDelayCountdown) },
	{ offsetof(FlightMissionState, globalUnitCraftCount),
	  offsetof(XvtSnapshotFlightMissionState, globalUnitCraftCount),
	  sizeof(((XvtSnapshotFlightMissionState*)0)->globalUnitCraftCount) },
};

void XvtSnapshot_EncodeFlightMissionState(XvtSnapshotFlightMissionState* record,
										  const FlightMissionState* live) {
	XvtSnapshot_CopyFields(record, (void*)live, g_FlightMissionStateFields,
						   sizeof(g_FlightMissionStateFields) / sizeof(g_FlightMissionStateFields[0]), 0);
}

void XvtSnapshot_DecodeFlightMissionState(FlightMissionState* live,
										  const XvtSnapshotFlightMissionState* record) {
	XvtSnapshot_CopyFields((void*)record, live, g_FlightMissionStateFields,
						   sizeof(g_FlightMissionStateFields) / sizeof(g_FlightMissionStateFields[0]), 1);
}
