# Adapted from OpenXWA's application bundle and resource staging.
set(XVT_VERSION "0.0.0-dev" CACHE STRING "OpenXvT package version")
target_compile_definitions(xvt PRIVATE OPENXVT_VERSION="${XVT_VERSION}")
set(XVT_AERON_DEFAULTS "${CMAKE_SOURCE_DIR}/aeron/config/scene3d_defaults.yaml")
set(XVT_DEFAULT_RESOURCES
    "${CMAKE_SOURCE_DIR}/resources/config.yaml"
    "${CMAKE_SOURCE_DIR}/resources/opt_alpha_overrides.yaml")
set(XVT_UI_FONTS
    "${CMAKE_SOURCE_DIR}/resources/assets/fonts/menu.fnt"
    "${CMAKE_SOURCE_DIR}/resources/assets/fonts/menu.png")
add_dependencies(xvt aeron_shaders xvt_shaders)
set(XVT_ALL_SHADER_OUTPUTS ${AERON_SHADER_OUTPUTS} ${XVT_SHADER_OUTPUTS})

if(APPLE)
    set(XVT_MACOS_BUILD_VERSION "1" CACHE STRING "macOS bundle build version")
    set(XVT_MACOS_BUNDLE_IDENTIFIER "org.openxvt.openxvt" CACHE STRING "macOS bundle identifier")
    set_target_properties(xvt PROPERTIES
        MACOSX_BUNDLE TRUE
        MACOSX_BUNDLE_INFO_PLIST "${CMAKE_SOURCE_DIR}/cmake/macos/Info.plist.in"
        INSTALL_RPATH "@executable_path/../Frameworks")
    set(XVT_MACOS_ICON "${CMAKE_SOURCE_DIR}/cmake/macos/OpenXvT.icns")
    target_sources(xvt PRIVATE "${XVT_MACOS_ICON}")
    set_source_files_properties("${XVT_MACOS_ICON}" PROPERTIES MACOSX_PACKAGE_LOCATION Resources)
    target_sources(xvt PRIVATE "${XVT_AERON_DEFAULTS}" ${XVT_DEFAULT_RESOURCES} ${XVT_ALL_SHADER_OUTPUTS})
    set_source_files_properties("${XVT_AERON_DEFAULTS}" PROPERTIES
        HEADER_FILE_ONLY TRUE
        MACOSX_PACKAGE_LOCATION Resources/resources/aeron)
    set_source_files_properties(${XVT_DEFAULT_RESOURCES} PROPERTIES
        HEADER_FILE_ONLY TRUE
        MACOSX_PACKAGE_LOCATION Resources/resources)
    target_sources(xvt PRIVATE ${XVT_UI_FONTS})
    set_source_files_properties(${XVT_UI_FONTS} PROPERTIES
        HEADER_FILE_ONLY TRUE MACOSX_PACKAGE_LOCATION Resources/resources/assets/fonts)
    set_source_files_properties(${XVT_ALL_SHADER_OUTPUTS} PROPERTIES
        GENERATED TRUE MACOSX_PACKAGE_LOCATION Resources/shaders)

    # FSR shaders are generated by a separate Aeron target. Stage on every build
    # so shader-only changes are also reflected in the bundle without a relink.
    add_custom_target(xvt_bundle_shaders ALL
        COMMAND "${CMAKE_COMMAND}"
            "-DXVT_BUNDLE_CONTENT_DIR=$<TARGET_BUNDLE_CONTENT_DIR:xvt>"
            "-DXVT_SHADER_SOURCE_DIR=${CMAKE_BINARY_DIR}/shaders"
            -P "${CMAKE_SOURCE_DIR}/cmake/macos/StageBundle.cmake"
        DEPENDS aeron_shaders xvt_shaders VERBATIM)
    add_dependencies(xvt xvt_bundle_shaders)
    install(TARGETS xvt BUNDLE DESTINATION . COMPONENT Runtime)
    set(XVT_PACKAGE_RESOURCE_DIR "OpenXvT.app/Contents/Resources")
    set(XVT_MACOS_DEPENDENCY_DIRS)
    foreach(prefix IN LISTS CMAKE_PREFIX_PATH)
        list(APPEND XVT_MACOS_DEPENDENCY_DIRS "${prefix}/lib")
    endforeach()
    configure_file("${CMAKE_SOURCE_DIR}/cmake/macos/FixupBundle.cmake.in"
        "${CMAKE_CURRENT_BINARY_DIR}/FixupMacBundle.cmake" @ONLY)
    install(SCRIPT "${CMAKE_CURRENT_BINARY_DIR}/FixupMacBundle.cmake" COMPONENT Runtime)
else()
    set(XVT_PACKAGE_RESOURCE_DIR ".")
    add_custom_target(xvt_resources
        COMMAND "${CMAKE_COMMAND}" -E make_directory "$<TARGET_FILE_DIR:xvt>/resources/assets/fonts"
        COMMAND "${CMAKE_COMMAND}" -E copy_if_different ${XVT_UI_FONTS}
            "$<TARGET_FILE_DIR:xvt>/resources/assets/fonts"
        COMMAND "${CMAKE_COMMAND}" -E make_directory "$<TARGET_FILE_DIR:xvt>/resources/aeron"
        COMMAND "${CMAKE_COMMAND}" -E copy_if_different "${XVT_AERON_DEFAULTS}"
            "$<TARGET_FILE_DIR:xvt>/resources/aeron/scene3d_defaults.yaml"
        COMMAND "${CMAKE_COMMAND}" -E copy_if_different ${XVT_DEFAULT_RESOURCES}
            "$<TARGET_FILE_DIR:xvt>/resources"
        DEPENDS "${XVT_AERON_DEFAULTS}" ${XVT_DEFAULT_RESOURCES} ${XVT_UI_FONTS} VERBATIM)
    add_dependencies(xvt xvt_resources)
    if(UNIX)
        set_target_properties(xvt PROPERTIES INSTALL_RPATH "$ORIGIN/lib")
    endif()
    install(TARGETS xvt RUNTIME DESTINATION . COMPONENT Runtime)
    install(FILES "${XVT_AERON_DEFAULTS}" DESTINATION resources/aeron COMPONENT Runtime)
    install(FILES ${XVT_DEFAULT_RESOURCES} DESTINATION resources COMPONENT Runtime)
    install(FILES ${XVT_UI_FONTS} DESTINATION resources/assets/fonts COMPONENT Runtime)
    foreach(format IN LISTS AERON_SHADER_FORMATS)
        if(format STREQUAL "MSL")
            set(extension msl)
        elseif(format STREQUAL "DXIL")
            set(extension dxil)
        else()
            set(extension spv)
        endif()
        install(DIRECTORY "${CMAKE_BINARY_DIR}/shaders/" DESTINATION shaders
            COMPONENT Runtime FILES_MATCHING PATTERN "*.${extension}")
    endforeach()
endif()

install(FILES "${CMAKE_SOURCE_DIR}/README.md"
    DESTINATION "${XVT_PACKAGE_RESOURCE_DIR}" COMPONENT Runtime)
install(FILES "${CMAKE_SOURCE_DIR}/licenses/undither.txt"
    DESTINATION "${XVT_PACKAGE_RESOURCE_DIR}/licenses" COMPONENT Runtime)
foreach(license IN ITEMS "bc7enc/LICENSE" "fidelityfx-fsr3/LICENSE.txt"
        "libjuice/LICENSE" "libyaml/License")
    get_filename_component(library "${license}" DIRECTORY)
    install(FILES "${CMAKE_SOURCE_DIR}/aeron/third_party/${license}"
        DESTINATION "${XVT_PACKAGE_RESOURCE_DIR}/licenses" RENAME "${library}.txt" COMPONENT Runtime)
endforeach()

if(WIN32)
    enable_language(RC)
    if(XVT_VERSION MATCHES "^([0-9]+)\\.([0-9]+)\\.([0-9]+)")
        set(XVT_VERSION_MAJOR ${CMAKE_MATCH_1})
        set(XVT_VERSION_MINOR ${CMAKE_MATCH_2})
        set(XVT_VERSION_PATCH ${CMAKE_MATCH_3})
    else()
        set(XVT_VERSION_MAJOR 0)
        set(XVT_VERSION_MINOR 0)
        set(XVT_VERSION_PATCH 0)
    endif()
    set(XVT_WINDOWS_ICON "${CMAKE_SOURCE_DIR}/cmake/windows/openxvt.ico")
    configure_file("${CMAKE_SOURCE_DIR}/cmake/windows/xvt.rc.in"
        "${CMAKE_CURRENT_BINARY_DIR}/xvt.rc" @ONLY)
    target_sources(xvt PRIVATE "${CMAKE_CURRENT_BINARY_DIR}/xvt.rc")
endif()
